const myFullThemes = [
    { name: "식물 (Cây cối)", words: [
        {w: "나무", img: "photo/Tree.avif", opts: ["나무","덤불","잎","뿌리"]},
        {w: "꽃", img: "photo/Flower.avif", opts: ["씨앗","꽃","줄기","꽃잎"]},
        {w: "잎", img: "photo/Leaf.avif", opts: ["열매","나뭇가지","잎","나무"]},
        {w: "풀", img: "photo/Grass.avif", opts: ["풀","흙","꽃","나무"]},
        {w: "나뭇가지", img: "photo/Branch.avif", opts: ["뿌리","나뭇가지","잎","줄기"]},
        {w: "뿌리", img: "photo/Root.avif", opts: ["열매","씨앗","뿌리","꽃"]},
        {w: "씨앗", img: "photo/Seed.avif", opts: ["풀","잎","나무","씨앗"]},
        {w: "열매", img: "photo/Fruit.avif", opts: ["꽃","열매","뿌리","나뭇가지"]},
        {w: "덤불", img: "photo/Bush.avif", opts: ["덤불","나무","풀","잎"]},
        {w: "숲", img: "photo/Forest.avif", opts: ["정원","공원","숲","농장"]}
    ]},
    { name: "과일 (Trái cây)", words: [
        {w: "사과", img: "photo/Apple.avif", opts: ["배","사과","포도","바나나"]},
        {w: "바나나", img: "photo/Banana.avif", opts: ["바나나","망고","사과","복숭아"]},
        {w: "오렌지", img: "photo/Orange.avif", opts: ["레몬","오렌지","키위","멜론"]},
        {w: "포도", img: "photo/Grapes.avif", opts: ["자두","체리","베리","포도"]},
        {w: "망고", img: "photo/Mango.avif", opts: ["레몬","파파야","망고","복숭아"]},
        {w: "수박", img: "photo/Watermelon.avif", opts: ["멜론","수박","키위","배"]},
        {w: "딸기", img: "photo/Strawberry.avif", opts: ["베리","딸기","체리","사과"]},
        {w: "파인애플", img: "photo/Pineapple.avif", opts: ["파인애플","코코넛","망고","오렌지"]},
        {w: "배", img: "photo/Pear.avif", opts: ["키위","사과","복숭아","배"]},
        {w: "복숭아", img: "photo/Peach.avif", opts: ["망고","자두","복숭아","오렌지"]}
    ]},
    { name: "동물 (Động vật)", words: [
        {w: "개", img: "photo/Dog.avif", opts: ["고양이","개","새","햄스터"]},
        {w: "고양이", img: "photo/Cat.avif", opts: ["개","고양이","생쥐","토끼"]},
        {w: "새", img: "photo/Bird.avif", opts: ["물고기","뱀","거미","새"]},
        {w: "토끼", img: "photo/Rabbit.avif", opts: ["토끼","햄스터","생쥐","개"]},
        {w: "생쥐", img: "photo/Mouse.avif", opts: ["생쥐","쥐","고양이","새"]},
        {w: "닭", img: "photo/Chicken.avif", opts: ["오리","닭","새","거위"]},
        {w: "오리", img: "photo/Duck.avif", opts: ["오리","닭","백조","물고기"]},
        {w: "돼지", img: "photo/Pig.avif", opts: ["소","돼지","양","말"]},
        {w: "소", img: "photo/Cow.avif", opts: ["소","염소","돼지","말"]},
        {w: "양", img: "photo/Sheep.avif", opts: ["염소","양","말","소"]}
    ]},
    { name: "색깔 (Màu sắc)", words: [
        {w: "빨간색", img: "photo/Red.avif", opts: ["파란색","빨간색","초록색","노란색"]},
        {w: "파란색", img: "photo/Blue.avif", opts: ["파란색","분홍색","검은색","하얀색"]},
        {w: "초록색", img: "photo/Green.avif", opts: ["빨간색","초록색","보라색","갈색"]},
        {w: "노란색", img: "photo/Yellow.avif", opts: ["주황색","노란색","하얀색","파란색"]},
        {w: "주황색", img: "photo/Orange.avif", opts: ["빨간색","노란색","분홍색","주황색"]},
        {w: "분홍색", img: "photo/Pink.avif", opts: ["보라색","빨간색","분홍색","하얀색"]},
        {w: "보라색", img: "photo/Purple.avif", opts: ["파란색","보라색","검은색","분홍색"]},
        {w: "검은색", img: "photo/Black.avif", opts: ["검은색","하얀색","회색","갈색"]},
        {w: "하얀색", img: "photo/White.avif", opts: ["하얀색","회색","노란색","파란색"]},
        {w: "갈색", img: "photo/Brown.avif", opts: ["검은색","주황색","빨간색","갈색"]}
    ]},
    { name: "숫자 (Số đếm)", words: [
        {w: "하나", img: "photo/One.avif", opts: ["하나","둘","셋","넷"]},
        {w: "둘", img: "photo/Two.avif", opts: ["다섯","둘","여섯","하나"]},
        {w: "셋", img: "photo/Three.avif", opts: ["셋","일곱","여덟","아홉"]},
        {w: "넷", img: "photo/Four.avif", opts: ["여섯","다섯","넷","셋"]},
        {w: "다섯", img: "photo/Five.avif", opts: ["넷","여섯","일곱","다섯"]},
        {w: "여섯", img: "photo/Six.avif", opts: ["일곱","여섯","여덟","다섯"]},
        {w: "일곱", img: "photo/Seven.avif", opts: ["아홉","여덟","일곱","여섯"]},
        {w: "여덟", img: "photo/Eight.avif", opts: ["아홉","여덟","열","일곱"]},
        {w: "아홉", img: "photo/Nine.avif", opts: ["여덟","열","하나","아홉"]},
        {w: "열", img: "photo/Ten.avif", opts: ["열","아홉","여덟","일곱"]}
    ]},
    { name: "가족 (Gia đình)", words: [
        {w: "어머니", img: "photo/Mother.avif", opts: ["아버지","어머니","아기","자매"]},
        {w: "아버지", img: "photo/Father.avif", opts: ["형제","아버지","삼촌","할아버지"]},
        {w: "아기", img: "photo/Baby.avif", opts: ["아기","엄마","아빠","선생님"]},
        {w: "자매", img: "photo/Sister.avif", opts: ["이모","형제","자매","어머니"]},
        {w: "형제", img: "photo/Brother.avif", opts: ["사촌","자매","형제","아버지"]},
        {w: "할머니", img: "photo/Grandmother.avif", opts: ["할머니","할아버지","고모","어머니"]},
        {w: "할아버지", img: "photo/Grandfather.avif", opts: ["아버지","할머니","삼촌","할아버지"]},
        {w: "삼촌", img: "photo/Uncle.avif", opts: ["아버지","이모","삼촌","할아버지"]},
        {w: "이모", img: "photo/Aunt.avif", opts: ["이모","삼촌","어머니","할머니"]},
        {w: "가족", img: "photo/Family.avif", opts: ["친구","가족","선생님","의사"]}
    ]},
    { name: "몸 (Cơ thể)", words: [
        {w: "손", img: "photo/Hand.avif", opts: ["발","손","팔","다리"]},
        {w: "눈", img: "photo/Eye.avif", opts: ["귀","눈","코","입"]},
        {w: "코", img: "photo/Nose.avif", opts: ["코","입술","얼굴","머리카락"]},
        {w: "입", img: "photo/Mouth.avif", opts: ["입","코","눈","귀"]},
        {w: "귀", img: "photo/Ear.avif", opts: ["코","눈","귀","입"]},
        {w: "발", img: "photo/Foot.avif", opts: ["팔","손","다리","발"]},
        {w: "다리", img: "photo/Leg.avif", opts: ["팔","다리","발","손"]},
        {w: "팔", img: "photo/Arm.avif", opts: ["손","다리","팔","발"]},
        {w: "손가락", img: "photo/Finger.avif", opts: ["손가락","발가락","손","발"]},
        {w: "머리", img: "photo/Head.avif", opts: ["얼굴","머리","머리카락","목"]}
    ]},
    { name: "옷 (Quần áo)", words: [
        {w: "모자", img: "photo/Hat.avif", opts: ["신발","모자","양말","셔츠"]},
        {w: "셔츠", img: "photo/Shirt.avif", opts: ["바지","셔츠","치마","코트"]},
        {w: "드레스", img: "photo/Dress.avif", opts: ["드레스","넥타이","벨트","가방"]},
        {w: "신발", img: "photo/Shoes.avif", opts: ["신발","양말","장화","샌들"]},
        {w: "양말", img: "photo/Socks.avif", opts: ["바지","신발","양말","모자"]},
        {w: "바지", img: "photo/Pants.avif", opts: ["셔츠","바지","드레스","치마"]},
        {w: "치마", img: "photo/Skirt.avif", opts: ["치마","드레스","바지","셔츠"]},
        {w: "코트", img: "photo/Coat.avif", opts: ["장갑","셔츠","모자","코트"]},
        {w: "장갑", img: "photo/Gloves.avif", opts: ["장갑","양말","신발","모자"]},
        {w: "스카프", img: "photo/Scarf.avif", opts: ["코트","스카프","모자","넥타이"]}
    ]},
    { name: "날씨 (Thời tiết)", words: [
        {w: "해", img: "photo/Sun.avif", opts: ["달","해","구름","비"]},
        {w: "비", img: "photo/Rain.avif", opts: ["바람","눈","비","폭풍"]},
        {w: "구름", img: "photo/Cloud.avif", opts: ["하늘","구름","별","해"]},
        {w: "눈", img: "photo/Snow.avif", opts: ["비","눈","바람","얼음"]},
        {w: "바람", img: "photo/Wind.avif", opts: ["해","폭풍","바람","비"]},
        {w: "폭풍", img: "photo/Storm.avif", opts: ["폭풍","바람","구름","비"]},
        {w: "무지개", img: "photo/Rainbow.avif", opts: ["하늘","무지개","별","달"]},
        {w: "달", img: "photo/Moon.avif", opts: ["달","해","별","구름"]},
        {w: "별", img: "photo/Star.avif", opts: ["달","별","해","하늘"]},
        {w: "하늘", img: "photo/Sky.avif", opts: ["하늘","구름","파란색","해"]}
    ]},
    { name: "장난감 (Đồ chơi)", words: [
        {w: "공", img: "photo/Ball.avif", opts: ["자동차","공","인형","레고"]},
        {w: "자동차", img: "photo/Car.avif", opts: ["비행기","자동차","기차","보트"]},
        {w: "인형", img: "photo/Doll.avif", opts: ["인형","곰","로봇","자전거"]},
        {w: "곰", img: "photo/Bear.avif", opts: ["곰","인형","개","고양이"]},
        {w: "로봇", img: "photo/Robot.avif", opts: ["기차","자동차","비행기","로봇"]},
        {w: "자전거", img: "photo/Bike.avif", opts: ["자동차","자전거","버스","비행기"]},
        {w: "비행기", img: "photo/Plane.avif", opts: ["비행기","자동차","보트","기차"]},
        {w: "보트", img: "photo/Boat.avif", opts: ["비행기","배","보트","자동차"]},
        {w: "기차", img: "photo/Train.avif", opts: ["기차","버스","트럭","자동차"]},
        {w: "연", img: "photo/Kite.avif", opts: ["구름","새","비행기","연"]}
    ]},
    { name: "직업 (Nghề nghiệp)", words: [
        {w: "의사", img: "photo/Doctor.avif", opts: ["간호사","의사","요리사","조종사"]},
        {w: "선생님", img: "photo/Teacher.avif", opts: ["가수","농부","선생님","경찰"]},
        {w: "경찰", img: "photo/Police.avif", opts: ["운전사","화가","경찰","치과의사"]},
        {w: "요리사", img: "photo/Chef.avif", opts: ["요리사","제빵사","웨이터","노동자"]},
        {w: "농부", img: "photo/Farmer.avif", opts: ["정원사","농부","수의사","조종사"]},
        {w: "조종사", img: "photo/Pilot.avif", opts: ["운전사","우주비행사","선원","조종사"]},
        {w: "간호사", img: "photo/Nurse.avif", opts: ["간호사","의사","치과의사","과학자"]},
        {w: "가수", img: "photo/Singer.avif", opts: ["무용수","배우","가수","작가"]},
        {w: "소방관", img: "photo/Fireman.avif", opts: ["소방관","군인","경찰","노동자"]},
        {w: "치과의사", img: "photo/Dentist.avif", opts: ["의사","간호사","치과의사","수의사"]}
    ]},
    { name: "모양 (Hình khối)", words: [
        {w: "원", img: "photo/Circle.avif", opts: ["사각형","원","별","하트"]},
        {w: "사각형", img: "photo/Square.avif", opts: ["타원","정육면체","사각형","선"]},
        {w: "삼각형", img: "photo/Triangle.avif", opts: ["상자","원","삼각형","별"]},
        {w: "별", img: "photo/Star.avif", opts: ["달","해","별","점"]},
        {w: "하트", img: "photo/Heart.avif", opts: ["하트","별","원","타원"]},
        {w: "타원", img: "photo/Oval.avif", opts: ["둥근","타원","사각형","정육면체"]},
        {w: "직사각형", img: "photo/Rectangle.avif", opts: ["사각형","상자","직사각형","선"]},
        {w: "다이아몬드", img: "photo/Diamond.avif", opts: ["별","원","하트","다이아몬드"]},
        {w: "정육면체", img: "photo/Cube.avif", opts: ["상자","정육면체","사각형","구"]},
        {w: "원기둥", img: "photo/Cylinder.avif", opts: ["원기둥","튜브","원뿔","둥근"]}
    ]},
    { name: "감정 (Cảm xúc)", words: [
        {w: "행복해요", img: "photo/Happy.avif", opts: ["슬퍼요","행복해요","화나요","졸려요"]},
        {w: "슬퍼요", img: "photo/Sad.avif", opts: ["웃겨요","용감해요","무서워요","슬퍼요"]},
        {w: "화나요", img: "photo/Angry.avif", opts: ["화나요","침착해요","피곤해요","부끄러워요"]},
        {w: "졸려요", img: "photo/Sleepy.avif", opts: ["지루해요","졸려요","행복해요","아파요"]},
        {w: "무서워요", img: "photo/Scared.avif", opts: ["용감해요","무서워요","화나요","웃겨요"]},
        {w: "놀랐어요", img: "photo/Surprised.avif", opts: ["놀랐어요","부끄러워요","침착해요","슬퍼요"]},
        {w: "배고파요", img: "photo/Hungry.avif", opts: ["목말라요","배고파요","배불러요","더워요"]},
        {w: "목말라요", img: "photo/Thirsty.avif", opts: ["추워요","아파요","배고파요","목말라요"]},
        {w: "아파요", img: "photo/Sick.avif", opts: ["아파요","건강해요","피곤해요","슬퍼요"]},
        {w: "용감해요", img: "photo/Brave.avif", opts: ["무서워요","튼튼해요","용감해요","약해요"]}
    ]},
    { name: "교통 (Giao thông)", words: [
        {w: "자동차", img: "photo/Car.avif", opts: ["버스","자동차","자전거","보트"]},
        {w: "자전거", img: "photo/Bicycle.avif", opts: ["오토바이","자전거","스쿠터","자동차"]},
        {w: "버스", img: "photo/Bus.avif", opts: ["기차","트럭","버스","밴"]},
        {w: "기차", img: "photo/Train.avif", opts: ["배","기차","비행기","버스"]},
        {w: "비행기", img: "photo/Airplane.avif", opts: ["로켓","비행기","헬리콥터","새"]},
        {w: "보트", img: "photo/Boat.avif", opts: ["보트","배","카누","잠수함"]},
        {w: "오토바이", img: "photo/Motorbike.avif", opts: ["자전거","밴","스쿠터","오토바이"]},
        {w: "트럭", img: "photo/Truck.avif", opts: ["자동차","트럭","화물차","지프"]},
        {w: "헬리콥터", img: "photo/Helicopter.avif", opts: ["헬리콥터","비행기","드론","로켓"]},
        {w: "배", img: "photo/Ship.avif", opts: ["보트","배","요트","잠수함"]}
    ]},
    { name: "바다 동물 (Động vật biển)", words: [
        {w: "물고기", img: "photo/Fish.avif", opts: ["게","물고기","상어","고래"]},
        {w: "상어", img: "photo/Shark.avif", opts: ["상어","돌고래","고래","물개"]},
        {w: "돌고래", img: "photo/Dolphin.avif", opts: ["문어","거북이","물고기","돌고래"]},
        {w: "문어", img: "photo/Octopus.avif", opts: ["오징어","불가사리","문어","해파리"]},
        {w: "거북이", img: "photo/Turtle.avif", opts: ["게","거북이","개구리","달팽이"]},
        {w: "고래", img: "photo/Whale.avif", opts: ["고래","상어","물고기","물개"]},
        {w: "게", img: "photo/Crab.avif", opts: ["바닷가재","게","새우","조개"]},
        {w: "불가사리", img: "photo/Starfish.avif", opts: ["불가사리","조개","산호","물고기"]},
        {w: "해마", img: "photo/Seahorse.avif", opts: ["뱀","장어","해마","물고기"]},
        {w: "해파리", img: "photo/Jellyfish.avif", opts: ["문어","해파리","산호","물"]}
    ]},
    { name: "거실 (Phòng khách)", words: [
        {w: "소파", img: "photo/Sofa.avif", opts: ["의자","침대","소파","책상"]},
        {w: "텔레비전", img: "photo/Television.avif", opts: ["라디오","텔레비전","전화기","컴퓨터"]},
        {w: "시계", img: "photo/Clock.avif", opts: ["손목시계","시계","거울","문"]},
        {w: "탁자", img: "photo/Table.avif", opts: ["책상","상자","의자","탁자"]},
        {w: "의자", img: "photo/Chair.avif", opts: ["소파","의자","스툴","침대"]},
        {w: "램프", img: "photo/Lamp.avif", opts: ["전등","램프","해","손전등"]},
        {w: "그림", img: "photo/Picture.avif", opts: ["그림","창문","벽","거울"]},
        {w: "커튼", img: "photo/Curtain.avif", opts: ["블라인드","커튼","문","시트"]},
        {w: "카펫", img: "photo/Carpet.avif", opts: ["매트","타일","바닥","카펫"]},
        {w: "리모컨", img: "photo/Remote.avif", opts: ["전화기","열쇠","리모컨","게임"]}
    ]},
    { name: "동작 (Hành động)", words: [
        {w: "달려요", img: "photo/Run.avif", opts: ["걸어요","달려요","점프해요","춤춰요"]},
        {w: "점프해요", img: "photo/Jump.avif", opts: ["앉아요","서요","점프해요","올라가요"]},
        {w: "수영해요", img: "photo/Swim.avif", opts: ["다이빙해요","수영해요","떠다녀요","목욕해요"]},
        {w: "춤춰요", img: "photo/Dance.avif", opts: ["춤춰요","노래해요","놀아요","읽어요"]},
        {w: "노래해요", img: "photo/Sing.avif", opts: ["말해요","노래해요","소리쳐요","들어요"]},
        {w: "먹어요", img: "photo/Eat.avif", opts: ["요리해요","빵을 구워요","마셔요","먹어요"]},
        {w: "마셔요", img: "photo/Drink.avif", opts: ["따라요","마셔요","먹어요","씻어요"]},
        {w: "읽어요", img: "photo/Read.avif", opts: ["써요","그려요","읽어요","봐요"]},
        {w: "써요", img: "photo/Write.avif", opts: ["색칠해요","타이핑해요","지워요","써요"]},
        {w: "자요", img: "photo/Sleep.avif", opts: ["꿈꿔요","자요","쉬어요","누워요"]}
    ]},
    { name: "야생 동물 (Động vật hoang dã)", words: [
        {w: "사자", img: "photo/Lion.avif", opts: ["호랑이","늑대","고양이","사자"]},
        {w: "호랑이", img: "photo/Tiger.avif", opts: ["표범","사자","호랑이","곰"]},
        {w: "코끼리", img: "photo/Elephant.avif", opts: ["하마","코끼리","코뿔소","기린"]},
        {w: "원숭이", img: "photo/Monkey.avif", opts: ["고릴라","원숭이","판다","침팬지"]},
        {w: "기린", img: "photo/Giraffe.avif", opts: ["사슴","말","기린","낙타"]},
        {w: "얼룩말", img: "photo/Zebra.avif", opts: ["말","당나귀","얼룩말","포니"]},
        {w: "곰", img: "photo/Bear.avif", opts: ["판다","곰","코알라","늑대"]},
        {w: "뱀", img: "photo/Snake.avif", opts: ["도마뱀","뱀","지렁이","개구리"]},
        {w: "악어", img: "photo/Crocodile.avif", opts: ["악어","앨리게이터","거북이","물고기"]},
        {w: "하마", img: "photo/Hippo.avif", opts: ["코끼리","코뿔소","돼지","하마"]}
    ]},
    { name: "시간 (Thời gian)", words: [
        {w: "낮", img: "photo/Day.avif", opts: ["밤","낮","정오","주일"]},
        {w: "밤", img: "photo/Night.avif", opts: ["아침","저녁","밤","어둠"]},
        {w: "아침", img: "photo/Morning.avif", opts: ["일출","아침","정오","이른"]},
        {w: "저녁", img: "photo/Evening.avif", opts: ["저녁","오후","일몰","늦은"]},
        {w: "오늘", img: "photo/Today.avif", opts: ["오늘","어제","내일","지금"]},
        {w: "주일", img: "photo/Week.avif", opts: ["달","해","주일","날"]},
        {w: "달", img: "photo/Month.avif", opts: ["계절","달","주일","해"]},
        {w: "해", img: "photo/Year.avif", opts: ["십년","시간","세기","해"]},
        {w: "초", img: "photo/Second.avif", opts: ["분","초","시간","순간"]},
        {w: "분", img: "photo/Minute.avif", opts: ["시간","초","분","시간"]}
    ]},
    { name: "학용품 (Đồ dùng học tập)", words: [
        {w: "연필", img: "photo/Pencil.avif", opts: ["연필","펜","자","크레용"]},
        {w: "책", img: "photo/Book.avif", opts: ["공책","책","종이","이야기"]},
        {w: "가방", img: "photo/Bag.avif", opts: ["배낭","상자","케이스","가방"]},
        {w: "자", img: "photo/Ruler.avif", opts: ["막대기","자","테이프","측정"]},
        {w: "지우개", img: "photo/Eraser.avif", opts: ["고무","지우개","연필깎이","펜"]},
        {w: "크레용", img: "photo/Crayon.avif", opts: ["크레용","마커","물감","연필"]},
        {w: "풀", img: "photo/Glue.avif", opts: ["테이프","반죽","끈적이는","풀"]},
        {w: "가위", img: "photo/Scissors.avif", opts: ["칼","자르기","종이","가위"]},
        {w: "책상", img: "photo/Desk.avif", opts: ["탁자","책상","의자","선반"]},
        {w: "교실", img: "photo/Classroom.avif", opts: ["학교","도서관","교실","체육관"]}
    ]},
    { name: "위치 (Vị trí)", words: [
        {w: "위", img: "photo/On.avif", opts: ["안","아래","위","너머"]},
        {w: "안", img: "photo/In.avif", opts: ["밖","안","사이","옆"]},
        {w: "아래", img: "photo/Under.avif", opts: ["위","아래쪽","아래","꼭대기"]},
        {w: "뒤", img: "photo/Behind.avif", opts: ["뒤","앞","옆","근처"]},
        {w: "앞", img: "photo/Front.avif", opts: ["뒤","가운데","앞","측면"]},
        {w: "사이", img: "photo/Between.avif", opts: ["중에서","옆에","사이","근처"]},
        {w: "옆에", img: "photo/Next_to.avif", opts: ["멀리","옆에","옆","맞은편"]},
        {w: "근처", img: "photo/Near.avif", opts: ["떨어져서","가까이","근처","멀리"]},
        {w: "멀리", img: "photo/Far.avif", opts: ["멀리","긴","근처","짧은"]},
        {w: "가운데", img: "photo/Middle.avif", opts: ["중심","가장자리","가운데","구석"]}
    ]},
    { name: "음식 (Thức ăn)", words: [
        {w: "빵", img: "photo/Bread.avif", opts: ["케이크","빵","밥","토스트"]},
        {w: "우유", img: "photo/Milk.avif", opts: ["물","주스","우유","탄산음료"]},
        {w: "달걀", img: "photo/Egg.avif", opts: ["고기","물고기","달걀","치즈"]},
        {w: "고기", img: "photo/Meat.avif", opts: ["스테이크","고기","닭고기","돼지고기"]},
        {w: "치즈", img: "photo/Cheese.avif", opts: ["치즈","버터","우유","요구르트"]},
        {w: "밥", img: "photo/Rice.avif", opts: ["곡물","밥","옥수수","콩"]},
        {w: "국수", img: "photo/Noodles.avif", opts: ["파스타","국","스파게티","국수"]},
        {w: "국", img: "photo/Soup.avif", opts: ["음료","물","국","육수"]},
        {w: "피자", img: "photo/Pizza.avif", opts: ["버거","피자","샌드위치","빵"]},
        {w: "햄버거", img: "photo/Hamburger.avif", opts: ["햄버거","감자튀김","피자","핫도그"]}
    ]},
    { name: "주방 (Nhà bếp)", words: [
        {w: "숟가락", img: "photo/Spoon.avif", opts: ["숟가락","포크","칼","국자"]},
        {w: "포크", img: "photo/Fork.avif", opts: ["숟가락","포크","도구","막대기"]},
        {w: "칼", img: "photo/Knife.avif", opts: ["날카로운","검","칼날","칼"]},
        {w: "그릇", img: "photo/Bowl.avif", opts: ["접시","그릇","컵","냄비"]},
        {w: "접시", img: "photo/Plate.avif", opts: ["요리","쟁반","접시","매트"]},
        {w: "컵", img: "photo/Cup.avif", opts: ["컵","유리잔","머그컵","병"]},
        {w: "유리잔", img: "photo/Glass.avif", opts: ["플라스틱","유리잔","꽃병","단지"]},
        {w: "냄비", img: "photo/Pot.avif", opts: ["프라이팬","주전자","냄비","가스레인지"]},
        {w: "프라이팬", img: "photo/Pan.avif", opts: ["튀김기","프라이팬","스킬렛","냄비"]},
        {w: "냉장고", img: "photo/Fridge.avif", opts: ["상자","냉동고","냉장고","아이스박스"]}
    ]},
    { name: "스포츠 (Thể thao)", words: [
        {w: "축구", img: "photo/Football.avif", opts: ["축구","공","축구","골"]},
        {w: "농구", img: "photo/Basketball.avif", opts: ["림","농구","그물","팀"]},
        {w: "수영", img: "photo/Swimming.avif", opts: ["수영","다이빙","수영장","물"]},
        {w: "달리기", img: "photo/Running.avif", opts: ["걷기","경주","트랙","달리기"]},
        {w: "테니스", img: "photo/Tennis.avif", opts: ["배드민턴","테니스","라켓","탁자"]},
        {w: "야구", img: "photo/Baseball.avif", opts: ["야구","배트","글러브","피칭"]},
        {w: "스케이트", img: "photo/Skating.avif", opts: ["스키","스케이트","얼음","롤러"]},
        {w: "스키", img: "photo/Skiing.avif", opts: ["눈","산","스키","추위"]},
        {w: "사이클링", img: "photo/Cycling.avif", opts: ["운전","바이킹","사이클링","타기"]},
        {w: "요가", img: "photo/Yoga.avif", opts: ["요가","스트레칭","운동","조용한"]}
    ]},
    { name: "심화 날씨 (Thời tiết nâng cao)", words: [
        {w: "눈사람", img: "photo/Snowman.avif", opts: ["얼음","겨울","눈사람","추위"]},
        {w: "천둥", img: "photo/Thunder.avif", opts: ["번개","천둥","소음","하늘"]},
        {w: "번개", img: "photo/Lightning.avif", opts: ["섬광","번개","전기","비"]},
        {w: "바람 부는", img: "photo/Windy.avif", opts: ["바람 부는","산들바람","통풍","폭풍우"]},
        {w: "안개 낀", img: "photo/Foggy.avif", opts: ["안개 낀","옅은 안개","회색","구름 낀"]},
        {w: "화창한", img: "photo/Sunny.avif", opts: ["더운","화창한","밝은","맑은"]},
        {w: "구름 낀", img: "photo/Cloudy.avif", opts: ["회색","어두운","구름 낀","하늘"]},
        {w: "매우 추운", img: "photo/Freezing.avif", opts: ["얼음 같은","추운","매우 추운","냉기"]},
        {w: "폭풍우 치는", img: "photo/Stormy.avif", opts: ["거친","심한","어두운","폭풍우 치는"]},
        {w: "허리케인", img: "photo/Hurricane.avif", opts: ["토네이도","사이클론","바람","허리케인"]}
    ]},
    { name: "장소 (Nơi chốn)", words: [
        {w: "공원", img: "photo/Park.avif", opts: ["공원","정원","놀이터","들판"]},
        {w: "해변", img: "photo/Beach.avif", opts: ["대양","해변","모래","섬"]},
        {w: "농장", img: "photo/Farm.avif", opts: ["농장","헛간","시골","들판"]},
        {w: "시장", img: "photo/Market.avif", opts: ["시장","상점","식료품","스토어"]},
        {w: "슈퍼마켓", img: "photo/Supermarket.avif", opts: ["쇼핑몰","건물","슈퍼마켓","홀"]},
        {w: "도서관", img: "photo/Library.avif", opts: ["책장","도서관","학교","조용한"]},
        {w: "병원", img: "photo/Hospital.avif", opts: ["진료소","건강","병원","침대"]},
        {w: "동물원", img: "photo/Zoo.avif", opts: ["우리","공원","동물들","동물원"]},
        {w: "박물관", img: "photo/Museum.avif", opts: ["예술","역사","갤러리","박물관"]},
        {w: "제과점", img: "photo/Bakery.avif", opts: ["제과점","빵","케이크","카페"]}
    ]},
    { name: "심화 교통 (Giao thông nâng cao)", words: [
        {w: "로켓", img: "photo/Rocket.avif", opts: ["로켓","우주","셔틀","별"]},
        {w: "구급차", img: "photo/Ambulance.avif", opts: ["밴","구급차","의사","병원"]},
        {w: "소방차", img: "photo/Fire_truck.avif", opts: ["소방차","화물차","빨간색","물"]},
        {w: "잠수함", img: "photo/Submarine.avif", opts: ["잠수함","배","수중","심해"]},
        {w: "트랙터", img: "photo/Tractor.avif", opts: ["트럭","트랙터","농장","들판"]},
        {w: "열기구", img: "photo/Balloon.avif", opts: ["공기","열기구","바구니","하늘"]},
        {w: "밴", img: "photo/Van.avif", opts: ["미니","자동차","밴","트럭"]},
        {w: "스쿠터", img: "photo/Scooter.avif", opts: ["베스파","자전거","바퀴","스쿠터"]},
        {w: "경찰차", img: "photo/Police_car.avif", opts: ["택시","경찰관","파란색","경찰차"]},
        {w: "택시", img: "photo/Taxi.avif", opts: ["우버","노란색","택시","운전사"]}
    ]},
    { name: "심화 가족 (Gia đình nâng cao)", words: [
        {w: "할아버지", img: "photo/Grandpa.avif", opts: ["노인","할아버지","남자","아버지"]},
        {w: "할머니", img: "photo/Grandma.avif", opts: ["여자","할머니","노인","어머니"]},
        {w: "아들", img: "photo/Son.avif", opts: ["아들","소년","아이","아기"]},
        {w: "딸", img: "photo/Daughter.avif", opts: ["딸","소녀","아이","아이"]},
        {w: "부모님", img: "photo/Parents.avif", opts: ["커플","부모님","집","성인"]},
        {w: "어린이들", img: "photo/Children.avif", opts: ["아이들","학급","어린이들","놀이"]},
        {w: "손주들", img: "photo/Grandchildren.avif", opts: ["작은","어린","가족","손주들"]},
        {w: "사촌", img: "photo/Cousin.avif", opts: ["친구","사촌","친척","쌍둥이"]},
        {w: "이모/고모", img: "photo/Auntie.avif", opts: ["숙녀","어머니","여자","이모/고모"]},
        {w: "이웃", img: "photo/Neighbor.avif", opts: ["집","거리","이웃","친구"]}
    ]},
    { name: "심화 자연 (Thiên nhiên nâng cao)", words: [
        {w: "돌", img: "photo/Stone.avif", opts: ["돌","바위","조약돌","딱딱한"]},
        {w: "모래", img: "photo/Sand.avif", opts: ["먼지","모래","해변","사막"]},
        {w: "조개껍데기", img: "photo/Shell.avif", opts: ["나선","바다","조개껍데기","해안"]},
        {w: "파도", img: "photo/Wave.avif", opts: ["물","서핑","파도","조수"]},
        {w: "산", img: "photo/Mountain.avif", opts: ["언덕","봉우리","등반","산"]},
        {w: "화산", img: "photo/Volcano.avif", opts: ["용암","화산","불","재"]},
        {w: "폭포", img: "photo/Waterfall.avif", opts: ["호수","시내","강","폭포"]},
        {w: "섬", img: "photo/Island.avif", opts: ["섬","지구","지도","야자수"]},
        {w: "동굴", img: "photo/Cave.avif", opts: ["구멍","동굴","어두운","돌"]},
        {w: "사막", img: "photo/Desert.avif", opts: ["사막","건조한","더운","모래"]}
    ]},
    { name: "심화 우주 (Vũ trụ nâng cao)", words: [
        {w: "지구", img: "photo/Earth.avif", opts: ["세계","행성","지구","지구본"]},
        {w: "달", img: "photo/Moon.avif", opts: ["은색","달","밤","우주"]},
        {w: "해", img: "photo/Sun.avif", opts: ["해","불","별","밝은"]},
        {w: "우주비행사", img: "photo/Astronaut.avif", opts: ["영웅","우주비행사","수트","조종사"]},
        {w: "외계인", img: "photo/Alien.avif", opts: ["초록색","괴물","UFO","외계인"]},
        {w: "행성", img: "photo/Planet.avif", opts: ["구체","우주","별","행성"]},
        {w: "은하", img: "photo/Galaxy.avif", opts: ["나선","은하","별들","빛"]},
        {w: "혜성", img: "photo/Comet.avif", opts: ["꼬리","불","혜성","유성"]},
        {w: "망원경", img: "photo/Telescope.avif", opts: ["망원경","유리","별들","보기"]},
        {w: "우주선", img: "photo/Spaceship.avif", opts: ["제트기","탈것","비행","우주선"]}
    ]}
];