const myFullThemes = [
    { name: "植物 (Cây cối)", words: [
        {w: "木", img: "photo/Tree.avif", opts: ["木","低木","葉","根"]},
        {w: "花", img: "photo/Flower.avif", opts: ["種","花","茎","花びら"]},
        {w: "葉っぱ", img: "photo/Leaf.avif", opts: ["果実","枝","葉っぱ","木"]},
        {w: "芝生", img: "photo/Grass.avif", opts: ["芝生","土","花","木"]},
        {w: "枝", img: "photo/Branch.avif", opts: ["根","枝","葉っぱ","茎"]},
        {w: "根", img: "photo/Root.avif", opts: ["果実","種","根","花"]},
        {w: "種", img: "photo/Seed.avif", opts: ["芝生","葉っぱ","木","種"]},
        {w: "果物", img: "photo/Fruit.avif", opts: ["花","果物","根","枝"]},
        {w: "低木", img: "photo/Bush.avif", opts: ["低木","木","芝生","葉っぱ"]},
        {w: "森", img: "photo/Forest.avif", opts: ["庭","公園","森","農場"]}
    ]},
    { name: "果物 (Trái cây)", words: [
        {w: "りんご", img: "photo/Apple.avif", opts: ["梨","りんご","ぶどう","バナナ"]},
        {w: "バナナ", img: "photo/Banana.avif", opts: ["バナナ","マンゴー","りんご","桃"]},
        {w: "オレンジ", img: "photo/Orange.avif", opts: ["レモン","オレンジ","キウイ","メロン"]},
        {w: "ぶどう", img: "photo/Grapes.avif", opts: ["プラム","さくらんぼ","ベリー","ぶどう"]},
        {w: "マンゴー", img: "photo/Mango.avif", opts: ["レモン","パパイヤ","マンゴー","桃"]},
        {w: "スイカ", img: "photo/Watermelon.avif", opts: ["メロン","スイカ","キウイ","梨"]},
        {w: "いちご", img: "photo/Strawberry.avif", opts: ["ベリー","いちご","さくらんぼ","りんご"]},
        {w: "パイナップル", img: "photo/Pineapple.avif", opts: ["パイナップル","ココナッツ","マンゴー","オレンジ"]},
        {w: "梨", img: "photo/Pear.avif", opts: ["キウイ","りんご","桃","梨"]},
        {w: "桃", img: "photo/Peach.avif", opts: ["マンゴー","プラム","桃","オレンジ"]}
    ]},
    { name: "動物 (Động vật)", words: [
        {w: "犬", img: "photo/Dog.avif", opts: ["猫","犬","鳥","ハムスター"]},
        {w: "猫", img: "photo/Cat.avif", opts: ["犬","猫","ねずみ","うさぎ"]},
        {w: "鳥", img: "photo/Bird.avif", opts: ["魚","ヘビ","クモ","鳥"]},
        {w: "うさぎ", img: "photo/Rabbit.avif", opts: ["うさぎ","ハムスター","ねずみ","犬"]},
        {w: "ねずみ", img: "photo/Mouse.avif", opts: ["ねずみ","ラット","猫","鳥"]},
        {w: "にわとり", img: "photo/Chicken.avif", opts: ["あひる","にわとり","鳥","がちょう"]},
        {w: "あひる", img: "photo/Duck.avif", opts: ["あひる","にわとり","白鳥","魚"]},
        {w: "豚", img: "photo/Pig.avif", opts: ["牛","豚","羊","馬"]},
        {w: "牛", img: "photo/Cow.avif", opts: ["牛","山羊","豚","馬"]},
        {w: "羊", img: "photo/Sheep.avif", opts: ["山羊","羊","馬","牛"]}
    ]},
    { name: "色 (Màu sắc)", words: [
        {w: "赤", img: "photo/Red.avif", opts: ["青","赤","緑","黄色"]},
        {w: "青", img: "photo/Blue.avif", opts: ["青","ピンク","黒","白"]},
        {w: "緑", img: "photo/Green.avif", opts: ["赤","緑","紫","茶色"]},
        {w: "黄色", img: "photo/Yellow.avif", opts: ["オレンジ","黄色","白","青"]},
        {w: "オレンジ", img: "photo/Orange.avif", opts: ["赤","黄色","ピンク","オレンジ"]},
        {w: "ピンク", img: "photo/Pink.avif", opts: ["紫","赤","ピンク","白"]},
        {w: "紫", img: "photo/Purple.avif", opts: ["青","紫","黒","ピンク"]},
        {w: "黒", img: "photo/Black.avif", opts: ["黒","白","灰色","茶色"]},
        {w: "白", img: "photo/White.avif", opts: ["白","灰色","黄色","青"]},
        {w: "茶色", img: "photo/Brown.avif", opts: ["黒","オレンジ","赤","茶色"]}
    ]},
    { name: "数字 (Số đếm)", words: [
        {w: "一", img: "photo/One.avif", opts: ["一","二","三","四"]},
        {w: "二", img: "photo/Two.avif", opts: ["五","二","六","一"]},
        {w: "三", img: "photo/Three.avif", opts: ["三","七","八","九"]},
        {w: "四", img: "photo/Four.avif", opts: ["六","五","四","三"]},
        {w: "五", img: "photo/Five.avif", opts: ["四","六","七","五"]},
        {w: "六", img: "photo/Six.avif", opts: ["七","六","八","五"]},
        {w: "七", img: "photo/Seven.avif", opts: ["九","八","七","六"]},
        {w: "八", img: "photo/Eight.avif", opts: ["九","八","十","七"]},
        {w: "九", img: "photo/Nine.avif", opts: ["八","十","一","九"]},
        {w: "十", img: "photo/Ten.avif", opts: ["十","九","八","七"]}
    ]},
    { name: "家族 (Gia đình)", words: [
        {w: "お母さん", img: "photo/Mother.avif", opts: ["お父さん","お母さん","赤ちゃん","姉妹"]},
        {w: "お父さん", img: "photo/Father.avif", opts: ["兄弟","お父さん","おじさん","おじいちゃん"]},
        {w: "赤ちゃん", img: "photo/Baby.avif", opts: ["赤ちゃん","ママ","パパ","先生"]},
        {w: "姉妹", img: "photo/Sister.avif", opts: ["おばさん","兄弟","姉妹","お母さん"]},
        {w: "兄弟", img: "photo/Brother.avif", opts: ["いとこ","姉妹","兄弟","お父さん"]},
        {w: "おばあちゃん", img: "photo/Grandmother.avif", opts: ["おばあちゃん","おじいちゃん","おばさん","お母さん"]},
        {w: "おじいちゃん", img: "photo/Grandfather.avif", opts: ["お父さん","おばあちゃん","おじさん","おじいちゃん"]},
        {w: "おじさん", img: "photo/Uncle.avif", opts: ["お父さん","おばさん","おじさん","おじいちゃん"]},
        {w: "おばさん", img: "photo/Aunt.avif", opts: ["おばさん","おじさん","お母さん","おばあちゃん"]},
        {w: "家族", img: "photo/Family.avif", opts: ["友達","家族","先生","医者"]}
    ]},
    { name: "体 (Cơ thể)", words: [
        {w: "手", img: "photo/Hand.avif", opts: ["足","手","腕","脚"]},
        {w: "目", img: "photo/Eye.avif", opts: ["耳","目","鼻","口"]},
        {w: "鼻", img: "photo/Nose.avif", opts: ["鼻","唇","顔","髪"]},
        {w: "口", img: "photo/Mouth.avif", opts: ["口","鼻","目","耳"]},
        {w: "耳", img: "photo/Ear.avif", opts: ["鼻","目","耳","口"]},
        {w: "足先", img: "photo/Foot.avif", opts: ["腕","手","脚","足先"]},
        {w: "脚", img: "photo/Leg.avif", opts: ["腕","脚","足先","手"]},
        {w: "腕", img: "photo/Arm.avif", opts: ["手","脚","腕","足先"]},
        {w: "指", img: "photo/Finger.avif", opts: ["指","足の指","手","足先"]},
        {w: "頭", img: "photo/Head.avif", opts: ["顔","頭","髪","首"]}
    ]},
    { name: "服 (Quần áo)", words: [
        {w: "帽子", img: "photo/Hat.avif", opts: ["靴","帽子","靴下","シャツ"]},
        {w: "シャツ", img: "photo/Shirt.avif", opts: ["ズボン","シャツ","スカート","コート"]},
        {w: "ドレス", img: "photo/Dress.avif", opts: ["ドレス","ネクタイ","ベルト","バッグ"]},
        {w: "靴", img: "photo/Shoes.avif", opts: ["靴","靴下","ブーツ","サンダル"]},
        {w: "靴下", img: "photo/Socks.avif", opts: ["ズボン","靴","靴下","帽子"]},
        {w: "ズボン", img: "photo/Pants.avif", opts: ["シャツ","ズボン","ドレス","スカート"]},
        {w: "スカート", img: "photo/Skirt.avif", opts: ["スカート","ドレス","ズボン","シャツ"]},
        {w: "コート", img: "photo/Coat.avif", opts: ["手袋","シャツ","帽子","コート"]},
        {w: "手袋", img: "photo/Gloves.avif", opts: ["手袋","靴下","靴","帽子"]},
        {w: "スカーフ", img: "photo/Scarf.avif", opts: ["コート","スカーフ","帽子","ネクタイ"]}
    ]},
    { name: "天気 (Thời tiết)", words: [
        {w: "太陽", img: "photo/Sun.avif", opts: ["月","太陽","雲","雨"]},
        {w: "雨", img: "photo/Rain.avif", opts: ["風","雪","雨","嵐"]},
        {w: "雲", img: "photo/Cloud.avif", opts: ["空","雲","星","太陽"]},
        {w: "雪", img: "photo/Snow.avif", opts: ["雨","雪","風","氷"]},
        {w: "風", img: "photo/Wind.avif", opts: ["太陽","嵐","風","雨"]},
        {w: "嵐", img: "photo/Storm.avif", opts: ["嵐","風","雲","雨"]},
        {w: "虹", img: "photo/Rainbow.avif", opts: ["空","虹","星","月"]},
        {w: "月", img: "photo/Moon.avif", opts: ["月","太陽","星","雲"]},
        {w: "星", img: "photo/Star.avif", opts: ["月","星","太陽","空"]},
        {w: "空", img: "photo/Sky.avif", opts: ["空","雲","青","太陽"]}
    ]},
    { name: "おもちゃ (Đồ chơi)", words: [
        {w: "ボール", img: "photo/Ball.avif", opts: ["車","ボール","人形","レゴ"]},
        {w: "車", img: "photo/Car.avif", opts: ["飛行機","車","電車","ボート"]},
        {w: "人形", img: "photo/Doll.avif", opts: ["人形","熊","ロボット","自転車"]},
        {w: "熊", img: "photo/Bear.avif", opts: ["熊","人形","犬","猫"]},
        {w: "ロボット", img: "photo/Robot.avif", opts: ["電車","車","飛行機","ロボット"]},
        {w: "自転車", img: "photo/Bike.avif", opts: ["車","自転車","バス","飛行機"]},
        {w: "飛行機", img: "photo/Plane.avif", opts: ["飛行機","車","ボート","電車"]},
        {w: "ボート", img: "photo/Boat.avif", opts: ["飛行機","船","ボート","車"]},
        {w: "電車", img: "photo/Train.avif", opts: ["電車","バス","トラック","車"]},
        {w: "凧", img: "photo/Kite.avif", opts: ["雲","鳥","飛行機","凧"]}
    ]},
    { name: "職業 (Nghề nghiệp)", words: [
        {w: "いしゃ", img: "photo/Doctor.avif", opts: ["かんごし","いしゃ","りょうりにん","パイロット"]},
        {w: "せんせい", img: "photo/Teacher.avif", opts: ["かしゅ","のうか","せんせい","けいさつ"]},
        {w: "けいさつ", img: "photo/Police.avif", opts: ["うんてんしゅ","げいじゅつか","けいさつ","はいしゃ"]},
        {w: "シェフ", img: "photo/Chef.avif", opts: ["シェフ","パンや","ウェイター","さぎょういん"]},
        {w: "のうか", img: "photo/Farmer.avif", opts: ["うえきや","のうか","じゅうい","パイロット"]},
        {w: "パイロット", img: "photo/Pilot.avif", opts: ["うんてんしゅ","うちゅうひこうし","せんいん","パイロット"]},
        {w: "かんごし", img: "photo/Nurse.avif", opts: ["かんごし","いしゃ","はいしゃ","かがくしゃ"]},
        {w: "かしゅ", img: "photo/Singer.avif", opts: ["ダンサー","はいゆう","かしゅ","さっか"]},
        {w: "しょうぼうし", img: "photo/Fireman.avif", opts: ["しょうぼうし","へいし","けいさつ","さぎょういん"]},
        {w: "はいしゃ", img: "photo/Dentist.avif", opts: ["いしゃ","かんごし","はいしゃ","じゅうい"]}
    ]},
    { name: "形 (Hình khối)", words: [
        {w: "まる", img: "photo/Circle.avif", opts: ["しかく","まる","ほし","ハート"]},
        {w: "しかく", img: "photo/Square.avif", opts: ["だえん","きょうぼう","しかく","せん"]},
        {w: "さんかく", img: "photo/Triangle.avif", opts: ["はこ","まる","さんかく","ほし"]},
        {w: "ほし", img: "photo/Star.avif", opts: ["つき","たいよう","ほし","てん"]},
        {w: "ハート", img: "photo/Heart.avif", opts: ["ハート","ほし","まる","だえん"]},
        {w: "だえん", img: "photo/Oval.avif", opts: ["まるい","だえん","しかく","きょうぼう"]},
        {w: "ちょうほうけい", img: "photo/Rectangle.avif", opts: ["しかく","はこ","ちょうほうけい","せん"]},
        {w: "ダイヤモンド", img: "photo/Diamond.avif", opts: ["ほし","まる","ハート","ダイヤモンド"]},
        {w: "立方体", img: "photo/Cube.avif", opts: ["はこ","立方体","しかく","きゅう"]},
        {w: "円柱", img: "photo/Cylinder.avif", opts: ["円柱","つつ","えんすい","まるい"]}
    ]},
    { name: "気持ち (Cảm xúc)", words: [
        {w: "うれしい", img: "photo/Happy.avif", opts: ["かなしい","うれしい","おこる","ねむい"]},
        {w: "かなしい", img: "photo/Sad.avif", opts: ["おもしろい","つよい","こわい","かなしい"]},
        {w: "おこる", img: "photo/Angry.avif", opts: ["おこる","しずか","つかれる","はずかしい"]},
        {w: "ねむい", img: "photo/Sleepy.avif", opts: ["たいくつ","ねむい","うれしい","びょうき"]},
        {w: "こわい", img: "photo/Scared.avif", opts: ["つよい","こわい","おこる","おもしろい"]},
        {w: "びっくり", img: "photo/Surprised.avif", opts: ["びっくり","はずかしい","しずか","かなしい"]},
        {w: "おなかがすいた", img: "photo/Hungry.avif", opts: ["のどがかわいた","おなかがすいた","いっぱい","あつい"]},
        {w: "のどがかわいた", img: "photo/Thirsty.avif", opts: ["さむい","びょうき","おなかがすいた","のどがかわいた"]},
        {w: "びょうき", img: "photo/Sick.avif", opts: ["びょうき","げんき","つかれる","かなしい"]},
        {w: "つよい", img: "photo/Brave.avif", opts: ["こわい","じょうぶ","つよい","よわい"]}
    ]},
    { name: "乗り物 (Giao thông)", words: [
        {w: "くるま", img: "photo/Car.avif", opts: ["バス","くるま","じてんしゃ","ふね"]},
        {w: "じてんしゃ", img: "photo/Bicycle.avif", opts: ["オートバイ","じてんしゃ","スクーター","くるま"]},
        {w: "バス", img: "photo/Bus.avif", opts: ["でんしゃ","トラック","バス","バン"]},
        {w: "でんしゃ", img: "photo/Train.avif", opts: ["ふね","でんしゃ","ひこうき","バス"]},
        {w: "ひこうき", img: "photo/Airplane.avif", opts: ["ロケット","ひこうき","ヘリコプター","とり"]},
        {w: "ふね", img: "photo/Boat.avif", opts: ["ふね","しっぷ","カヌー","せんすいかん"]},
        {w: "オートバイ", img: "photo/Motorbike.avif", opts: ["じてんしゃ","バン","スクーター","オートバイ"]},
        {w: "トラック", img: "photo/Truck.avif", opts: ["くるま","トラック","ローリー","ジープ"]},
        {w: "ヘリコプター", img: "photo/Helicopter.avif", opts: ["ヘリコプター","ひこうき","ドローン","ロケット"]},
        {w: "しっぷ", img: "photo/Ship.avif", opts: ["ふね","しっぷ","ヨット","せんすいかん"]}
    ]},
    { name: "海の動物 (Động vật biển)", words: [
        {w: "さかな", img: "photo/Fish.avif", opts: ["かに","さかな","さめ","くじら"]},
        {w: "さめ", img: "photo/Shark.avif", opts: ["さめ","いるか","くじら","あざらし"]},
        {w: "いるか", img: "photo/Dolphin.avif", opts: ["たこ","かめ","さかな","いるか"]},
        {w: "たこ", img: "photo/Octopus.avif", opts: ["いか","ひとで","たこ","くらげ"]},
        {w: "かめ", img: "photo/Turtle.avif", opts: ["かに","かめ","かえる","かたつむり"]},
        {w: "くじら", img: "photo/Whale.avif", opts: ["くじら","さめ","さかな","あざらし"]},
        {w: "かに", img: "photo/Crab.avif", opts: ["ロブスター","かに","えび","かい"]},
        {w: "ひとで", img: "photo/Starfish.avif", opts: ["ひとで","かい","さんご","さかな"]},
        {w: "たつのおとしご", img: "photo/Seahorse.avif", opts: ["へび","うなぎ","たつのおとしご","さかな"]},
        {w: "くらげ", img: "photo/Jellyfish.avif", opts: ["たこ","くらげ","さんご","みず"]}
    ]},
    { name: "リビングルーム (Phòng khách)", words: [
        {w: "ソファ", img: "photo/Sofa.avif", opts: ["いす","ベッド","ソファ","つくえ"]},
        {w: "テレビ", img: "photo/Television.avif", opts: ["ラジオ","テレビ","でんわ","コンピュータ"]},
        {w: "とけい", img: "photo/Clock.avif", opts: ["うでどけい","とけい","かがみ","ドア"]},
        {w: "テーブル", img: "photo/Table.avif", opts: ["つくえ","はこ","いす","テーブル"]},
        {w: "いす", img: "photo/Chair.avif", opts: ["ソファ","いす","スツール","ベッド"]},
        {w: "ランプ", img: "photo/Lamp.avif", opts: ["ライト","ランプ","たいよう","かいちゅうでんとう"]},
        {w: "え", img: "photo/Picture.avif", opts: ["え","まど","かべ","かがみ"]},
        {w: "カーテン", img: "photo/Curtain.avif", opts: ["ブラインド","カーテン","ドア","シーツ"]},
        {w: "じゅうたん", img: "photo/Carpet.avif", opts: ["マット","タイル","ゆか","じゅうたん"]},
        {w: "リモコン", img: "photo/Remote.avif", opts: ["でんわ","かぎ","リモコン","ゲーム"]}
    ]},
    { name: "動作 (Hành động)", words: [
        {w: "はしる", img: "photo/Run.avif", opts: ["あるく","はしる","ジャンプ","おどる"]},
        {w: "ジャンプ", img: "photo/Jump.avif", opts: ["すわる","たつ","ジャンプ","のぼる"]},
        {w: "およぐ", img: "photo/Swim.avif", opts: ["もぐる","およぐ","うく","おふろ"]},
        {w: "おどる", img: "photo/Dance.avif", opts: ["おどる","うたう","あそぶ","よむ"]},
        {w: "うたう", img: "photo/Sing.avif", opts: ["はなす","うたう","さけぶ","きく"]},
        {w: "たべる", img: "photo/Eat.avif", opts: ["りょうり","やく","のむ","たべる"]},
        {w: "のむ", img: "photo/Drink.avif", opts: ["そそぐ","のむ","たべる","あらわれる"]},
        {w: "よむ", img: "photo/Read.avif", opts: ["かく","えをかく","よむ","みる"]},
        {w: "かく", img: "photo/Write.avif", opts: ["ぬる","タイプ","けす","かく"]},
        {w: "ねる", img: "photo/Sleep.avif", opts: ["ゆめ","ねる","やすむ","よこたわる"]}
    ]},
    { name: "野生動物 (Động vật hoang dã)", words: [
        {w: "ライオン", img: "photo/Lion.avif", opts: ["トラ","おおかみ","ねこ","ライオン"]},
        {w: "トラ", img: "photo/Tiger.avif", opts: ["ヒョウ","ライオン","トラ","くま"]},
        {w: "ぞう", img: "photo/Elephant.avif", opts: ["カバ","ぞう","サイ","きりん"]},
        {w: "さる", img: "photo/Monkey.avif", opts: ["ゴリラ","さる","パンダ","チンパンジー"]},
        {w: "きりん", img: "photo/Giraffe.avif", opts: ["しか","うま","きりん","らくだ"]},
        {w: "しまうま", img: "photo/Zebra.avif", opts: ["うま","ろば","しまうま","ポニー"]},
        {w: "くま", img: "photo/Bear.avif", opts: ["パンダ","くま","コアラ","おおかみ"]},
        {w: "へび", img: "photo/Snake.avif", opts: ["とかげ","へび","みみず","かえる"]},
        {w: "わに", img: "photo/Crocodile.avif", opts: ["わに","アリゲーター","かめ","さかな"]},
        {w: "カバ", img: "photo/Hippo.avif", opts: ["ぞう","サイ","ぶた","カバ"]}
    ]},
    { name: "時間 (Thời gian)", words: [
        {w: "ひる", img: "photo/Day.avif", opts: ["よる","ひる","しょうご","しゅう"]},
        {w: "よる", img: "photo/Night.avif", opts: ["あさ","ばん","よる","くらい"]},
        {w: "あさ", img: "photo/Morning.avif", opts: ["ひので","あさ","しょうご","はやい"]},
        {w: "ばん", img: "photo/Evening.avif", opts: ["ばん","ごご","ゆうやけ","おそい"]},
        {w: "きょう", img: "photo/Today.avif", opts: ["きょう","きのう","あした","いま"]},
        {w: "しゅう", img: "photo/Week.avif", opts: ["つき","とし","しゅう","ひ"]},
        {w: "つき", img: "photo/Month.avif", opts: ["きせつ","つき","しゅう","とし"]},
        {w: "とし", img: "photo/Year.avif", opts: ["じゅうねん","とき","せいき","とし"]},
        {w: "びょう", img: "photo/Second.avif", opts: ["ぷん","びょう","じかん","しゅんかん"]},
        {w: "ぷん", img: "photo/Minute.avif", opts: ["じかん","びょう","ぷん","とき"]}
    ]},
    { name: "学校用品 (Đồ dùng học tập)", words: [
        {w: "えんぴつ", img: "photo/Pencil.avif", opts: ["えんぴつ","ペン","ものさし","クレヨン"]},
        {w: "ほん", img: "photo/Book.avif", opts: ["ノート","ほん","かみ","おはなし"]},
        {w: "かばん", img: "photo/Bag.avif", opts: ["リュック","はこ","ケース","かばん"]},
        {w: "ものさし", img: "photo/Ruler.avif", opts: ["ぼう","ものさし","テープ","はかる"]},
        {w: "けしごむ", img: "photo/Eraser.avif", opts: ["ラバー","けしごむ","えんぴつけずり","ペン"]},
        {w: "クレヨン", img: "photo/Crayon.avif", opts: ["クレヨン","マジック","えのぐ","えんぴつ"]},
        {w: "のり", img: "photo/Glue.avif", opts: ["テープ","ペースト","ねばねば","のり"]},
        {w: "はさみ", img: "photo/Scissors.avif", opts: ["ナイフ","きる","かみ","はさみ"]},
        {w: "つくえ", img: "photo/Desk.avif", opts: ["テーブル","つくえ","いす","たな"]},
        {w: "きょうしつ", img: "photo/Classroom.avif", opts: ["がっこう","としょかん","きょうしつ","ジム"]}
    ]},
    { name: "場所 (Vị trí)", words: [
        {w: "うえ", img: "photo/On.avif", opts: ["なか","した","うえ","こえる"]},
        {w: "なか", img: "photo/In.avif", opts: ["そと","なか","あいだ","そば"]},
        {w: "した", img: "photo/Under.avif", opts: ["うえ","したほう","した","てっぺん"]},
        {w: "うしろ", img: "photo/Behind.avif", opts: ["うしろ","まえ","そば","ちかい"]},
        {w: "まえ", img: "photo/Front.avif", opts: ["うしろ","まんなか","まえ","よこ"]},
        {w: "あいだ", img: "photo/Between.avif", opts: ["かこまれて","つぎ","あいだ","ちかい"]},
        {w: "となり", img: "photo/Next_to.avif", opts: ["とおい","となり","そば","はんたい"]},
        {w: "ちかい", img: "photo/Near.avif", opts: ["はなれて","すぐ","ちかい","とおい"]},
        {w: "とおい", img: "photo/Far.avif", opts: ["とおい","ながい","ちかい","みじかい"]},
        {w: "まんなか", img: "photo/Middle.avif", opts: ["ちゅうしん","はし","まんなか","かど"]}
    ]},
    { name: "たべもの (Thức ăn)", words: [
        {w: "パン", img: "photo/Bread.avif", opts: ["ケーキ","パン","ごはん","トースト"]},
        {w: "ぎゅうにゅう", img: "photo/Milk.avif", opts: ["みず","ジュース","ぎゅうにゅう","ソーダ"]},
        {w: "たまご", img: "photo/Egg.avif", opts: ["にく","さかな","たまご","チーズ"]},
        {w: "にく", img: "photo/Meat.avif", opts: ["ステーキ","にく","とり","ぶた"]},
        {w: "チーズ", img: "photo/Cheese.avif", opts: ["チーズ","バター","ぎゅうにゅう","ヨーグルト"]},
        {w: "ごはん", img: "photo/Rice.avif", opts: ["こくもつ","ごはん","とうもろこし","まめ"]},
        {w: "めん", img: "photo/Noodles.avif", opts: ["パスタ","スープ","スパゲッティ","めん"]},
        {w: "スープ", img: "photo/Soup.avif", opts: ["のみもの","みず","スープ","だし"]},
        {w: "ピザ", img: "photo/Pizza.avif", opts: ["ハンバーガー","ピザ","サンドイッチ","パン"]},
        {w: "ハンバーガー", img: "photo/Hamburger.avif", opts: ["ハンバーガー","ポテト","ピザ","ホットドッグ"]}
    ]},
    { name: "キッチン (Nhà bếp)", words: [
        {w: "スプーン", img: "photo/Spoon.avif", opts: ["スプーン","フォーク","ナイフ","おたま"]},
        {w: "フォーク", img: "photo/Fork.avif", opts: ["スプーン","フォーク","どうぐ","はし"]},
        {w: "ナイフ", img: "photo/Knife.avif", opts: ["するどい","つるぎ","は","ナイフ"]},
        {w: "わん", img: "photo/Bowl.avif", opts: ["さら","わん","カップ","なべ"]},
        {w: "さら", img: "photo/Plate.avif", opts: ["さら(料理)","トレイ","さら","マット"]},
        {w: "カップ", img: "photo/Cup.avif", opts: ["カップ","グラス","マグ","ボトル"]},
        {w: "グラス", img: "photo/Glass.avif", opts: ["プラスチック","グラス","かびん","びん"]},
        {w: "なべ", img: "photo/Pot.avif", opts: ["フライパン","やかん","なべ","コンロ"]},
        {w: "フライパン", img: "photo/Pan.avif", opts: ["あげもの","フライパン","スキレット","なべ"]},
        {w: "れいぞうこ", img: "photo/Fridge.avif", opts: ["はこ","れいとうこ","れいぞうこ","クーラー"]}
    ]},
    { name: "スポーツ (Thể thao)", words: [
        {w: "サッカー", img: "photo/Football.avif", opts: ["フットボール","ボール","サッカー","ゴール"]},
        {w: "バスケットボール", img: "photo/Basketball.avif", opts: ["リング","バスケットボール","ネット","チーム"]},
        {w: "すいえい", img: "photo/Swimming.avif", opts: ["すいえい","とびこみ","プール","みず"]},
        {w: "はしること", img: "photo/Running.avif", opts: ["あるくこと","レース","トラック","はしること"]},
        {w: "テニス", img: "photo/Tennis.avif", opts: ["バドミントン","テニス","ラケット","テーブル"]},
        {w: "やきゅう", img: "photo/Baseball.avif", opts: ["やきゅう","バット","グローブ","ピッチ"]},
        {w: "スケート", img: "photo/Skating.avif", opts: ["スキー","スケート","こおり","ローラー"]},
        {w: "スキー", img: "photo/Skiing.avif", opts: ["ゆき","やま","スキー","さむい"]},
        {w: "サイクリング", img: "photo/Cycling.avif", opts: ["うんてん","バイク","サイクリング","のる"]},
        {w: "ヨガ", img: "photo/Yoga.avif", opts: ["ヨガ","ストレッチ","うんどう","しずか"]}
    ]},
    { name: "天気詳細 (Thời tiết nâng cao)", words: [
        {w: "ゆきだるま", img: "photo/Snowman.avif", opts: ["こおり","ふゆ","ゆきだるま","さむい"]},
        {w: "かみなり", img: "photo/Thunder.avif", opts: ["いなずま","かみなり","おと","そら"]},
        {w: "いなずま", img: "photo/Lightning.avif", opts: ["フラッシュ","いなずま","でんき","あめ"]},
        {w: "かぜがつよい", img: "photo/Windy.avif", opts: ["かぜがつよい","そよかぜ","かぜとおし","あらし"]},
        {w: "きり", img: "photo/Foggy.avif", opts: ["きり","もや","はいいろ","くもり"]},
        {w: "はれ", img: "photo/Sunny.avif", opts: ["あつい","はれ","あかるい","クリア"]},
        {w: "くもり", img: "photo/Cloudy.avif", opts: ["はいいろ","くらい","くもり","そら"]},
        {w: "こごえる", img: "photo/Freezing.avif", opts: ["つめたい","さむい","こごえる","ひえ"]},
        {w: "あらし", img: "photo/Stormy.avif", opts: ["あらい","ひどい","くらい","あらし"]},
        {w: "ハリケーン", img: "photo/Hurricane.avif", opts: ["たつまき","サイクロン","かぜ","ハリケーン"]}
    ]},
    { name: "プレース (Nơi chốn nâng cao)", words: [
        {w: "こうえん", img: "photo/Park.avif", opts: ["こうえん","にわ","あそびば","はら"]},
        {w: "かいがん", img: "photo/Beach.avif", opts: ["うみ","かいがん","すな","しま"]},
        {w: "のうじょう", img: "photo/Farm.avif", opts: ["のうじょう","なや","いなか","はら"]},
        {w: "いちば", img: "photo/Market.avif", opts: ["いちば","みせ","しょくりょうひん","ストア"]},
        {w: "スーパー", img: "photo/Supermarket.avif", opts: ["モール","たてもの","スーパー","ホール"]},
        {w: "としょかん", img: "photo/Library.avif", opts: ["ほんだな","としょかん","がっこう","しずか"]},
        {w: "びょういん", img: "photo/Hospital.avif", opts: ["クリニック","けんこう","びょういん","ベッド"]},
        {w: "どうぶつえん", img: "photo/Zoo.avif", opts: ["おり","こうえん","どうぶつ","どうぶつえん"]},
        {w: "はくぶつかん", img: "photo/Museum.avif", opts: ["アート","れきし","ギャラリー","はくぶつかん"]},
        {w: "パンや", img: "photo/Bakery.avif", opts: ["パンや","パン","ケーキ","カフェ"]}
    ]},
    { name: "乗り物詳細 (Giao thông nâng cao)", words: [
        {w: "ロケット", img: "photo/Rocket.avif", opts: ["ロケット","うちゅう","シャトル","ほし"]},
        {w: "きゅうきゅうしゃ", img: "photo/Ambulance.avif", opts: ["バン","きゅうきゅうしゃ","いしゃ","びょういん"]},
        {w: "しょうぼうしゃ", img: "photo/Fire_truck.avif", opts: ["しょうぼうしゃ","ローリー","あか","みず"]},
        {w: "せんすいかん", img: "photo/Submarine.avif", opts: ["せんすいかん","ふね","すいちゅう","ふかい"]},
        {w: "トラクター", img: "photo/Tractor.avif", opts: ["トラック","トラクター","のうじょう","はら"]},
        {w: "ききゅう", img: "photo/Balloon.avif", opts: ["くうき","ききゅう","バスケット","そら"]},
        {w: "バン", img: "photo/Van.avif", opts: ["ミニ","くるま","バン","トラック"]},
        {w: "スクーター", img: "photo/Scooter.avif", opts: ["ベスパ","じてんしゃ","わ","スクーター"]},
        {w: "パトカー", img: "photo/Police_car.avif", opts: ["タクシー","けいかん","あお","パトカー"]},
        {w: "タクシー", img: "photo/Taxi.avif", opts: ["ウーバー","きいろ","タクシー","うんてんしゅ"]}
    ]},
    { name: "家族詳細 (Gia đình nâng cao)", words: [
        {w: "おじいちゃん", img: "photo/Grandpa.avif", opts: ["としより","おじいちゃん","おとこ","お父さん"]},
        {w: "おばあちゃん", img: "photo/Grandma.avif", opts: ["おんな","おばあちゃん","としより","お母さん"]},
        {w: "むすこ", img: "photo/Son.avif", opts: ["むすこ","おとこのこ","こども","赤ちゃん"]},
        {w: "むすめ", img: "photo/Daughter.avif", opts: ["むすめ","おんなのこ","こども","こ"]},
        {w: "りょうしん", img: "photo/Parents.avif", opts: ["ふうふ","りょうしん","いえ","おとな"]},
        {w: "こどもたち", img: "photo/Children.avif", opts: ["キッズ","クラス","こどもたち","あそび"]},
        {w: "まご", img: "photo/Grandchildren.avif", opts: ["ちいさい","わかい","かぞく","まご"]},
        {w: "いとこ", img: "photo/Cousin.avif", opts: ["ともだち","いとこ","しんせき","ふたご"]},
        {w: "おばさん", img: "photo/Auntie.avif", opts: ["レディ","お母さん","おんな","おばさん"]},
        {w: "となりびと", img: "photo/Neighbor.avif", opts: ["いえ","みち","となりびと","ともだち"]}
    ]},
    { name: "自然詳細 (Thiên nhiên nâng cao)", words: [
        {w: "いし", img: "photo/Stone.avif", opts: ["いし","いわ","こいし","かたい"]},
        {w: "すな", img: "photo/Sand.avif", opts: ["ちり","すな","かいがん","さばく"]},
        {w: "かいがら", img: "photo/Shell.avif", opts: ["うずまき","うみ","かいがら","なぎさ"]},
        {w: "なみ", img: "photo/Wave.avif", opts: ["みず","サーフ","なみ","しお"]},
        {w: "やま", img: "photo/Mountain.avif", opts: ["おか","ちょうじょう","のぼる","やま"]},
        {w: "かざん", img: "photo/Volcano.avif", opts: ["ようがん","かざん","ひ","はい"]},
        {w: "たき", img: "photo/Waterfall.avif", opts: ["みずうみ","おがわ","かわ","たき"]},
        {w: "しま", img: "photo/Island.avif", opts: ["しま","ちきゅう","ちず","やし"]},
        {w: "どうくつ", img: "photo/Cave.avif", opts: ["あな","どうくつ","くらい","いし"]},
        {w: "さばく", img: "photo/Desert.avif", opts: ["さばく","かわいた","あつい","すな"]}
    ]},
    { name: "宇宙 (Vũ trụ)", words: [
        {w: "ちきゅう", img: "photo/Earth.avif", opts: ["せかい","わくせい","ちきゅう","ちきゅうぎ"]},
        {w: "つき", img: "photo/Moon.avif", opts: ["ぎんいろ","つき","よる","うちゅう"]},
        {w: "たいよう", img: "photo/Sun.avif", opts: ["たいよう","ひ","ほし","あかるい"]},
        {w: "うちゅうひこうし", img: "photo/Astronaut.avif", opts: ["ヒーロー","うちゅうひこうし","スーツ","パイロット"]},
        {w: "うちゅうじん", img: "photo/Alien.avif", opts: ["みどり","モンスター","UFO","うちゅうじん"]},
        {w: "わくせい", img: "photo/Planet.avif", opts: ["きゅう","うちゅう","ほし","わくせい"]},
        {w: "ぎんが", img: "photo/Galaxy.avif", opts: ["うずまき","ぎんが","ほしぼし","ひかり"]},
        {w: "ほうきぼし", img: "photo/Comet.avif", opts: ["お","ひ","ほうきぼし","ながれぼし"]},
        {w: "ぼうえんきょう", img: "photo/Telescope.avif", opts: ["ぼうえんきょう","ガラス","ほしぼし","みる"]},
        {w: "うちゅうせん", img: "photo/Spaceship.avif", opts: ["ジェット","のりもの","とぶ","うちゅうせん"]}
    ]}
];