const myFullThemes = [
    { name: "Cây cối", words: [
        {w: "Tree", img: "photo/Tree.avif", opts: ["Tree","Bush","Leaf","Root"]},
        {w: "Flower", img: "photo/Flower.avif", opts: ["Seed","Flower","Stem","Petal"]},
        {w: "Leaf", img: "photo/Leaf.avif", opts: ["Fruit","Branch","Leaf","Tree"]},
        {w: "Grass", img: "photo/Grass.avif", opts: ["Grass","Soil","Flower","Tree"]},
        {w: "Branch", img: "photo/Branch.avif", opts: ["Root","Branch","Leaf","Stem"]},
        {w: "Root", img: "photo/Root.avif", opts: ["Fruit","Seed","Root","Flower"]},
        {w: "Seed", img: "photo/Seed.avif", opts: ["Grass","Leaf","Tree","Seed"]},
        {w: "Fruit", img: "photo/Fruit.avif", opts: ["Flower","Fruit","Root","Branch"]},
        {w: "Bush", img: "photo/Bush.avif", opts: ["Bush","Tree","Grass","Leaf"]},
        {w: "Forest", img: "photo/Forest.avif", opts: ["Garden","Park","Forest","Farm"]}
    ]},
    { name: "Trái cây", words: [
        {w: "Apple", img: "photo/Apple.avif", opts: ["Pear","Apple","Grape","Banana"]},
        {w: "Banana", img: "photo/Banana.avif", opts: ["Banana","Mango","Apple","Peach"]},
        {w: "Orange", img: "photo/Orange.avif", opts: ["Lemon","Orange","Kiwi","Melon"]},
        {w: "Grapes", img: "photo/Grapes.avif", opts: ["Plum","Cherry","Berry","Grapes"]},
        {w: "Mango", img: "photo/Mango.avif", opts: ["Lemon","Papaya","Mango","Peach"]},
        {w: "Watermelon", img: "photo/Watermelon.avif", opts: ["Melon","Watermelon","Kiwi","Pear"]},
        {w: "Strawberry", img: "photo/Strawberry.avif", opts: ["Berry","Strawberry","Cherry","Apple"]},
        {w: "Pineapple", img: "photo/Pineapple.avif", opts: ["Pineapple","Coconut","Mango","Orange"]},
        {w: "Pear", img: "photo/Pear.avif", opts: ["Kiwi","Apple","Peach","Pear"]},
        {w: "Peach", img: "photo/Peach.avif", opts: ["Mango","Plum","Peach","Orange"]}
    ]},
    { name: "Động vật", words: [
        {w: "Dog", img: "photo/Dog.avif", opts: ["Cat","Dog","Bird","Hamster"]},
        {w: "Cat", img: "photo/Cat.avif", opts: ["Dog","Cat","Mouse","Rabbit"]},
        {w: "Bird", img: "photo/Bird.avif", opts: ["Fish","Snake","Spider","Bird"]},
        {w: "Rabbit", img: "photo/Rabbit.avif", opts: ["Rabbit","Hamster","Mouse","Dog"]},
        {w: "Mouse", img: "photo/Mouse.avif", opts: ["Mouse","Rat","Cat","Bird"]},
        {w: "Chicken", img: "photo/Chicken.avif", opts: ["Duck","Chicken","Bird","Goose"]},
        {w: "Duck", img: "photo/Duck.avif", opts: ["Duck","Chicken","Swan","Fish"]},
        {w: "Pig", img: "photo/Pig.avif", opts: ["Cow","Pig","Sheep","Horse"]},
        {w: "Cow", img: "photo/Cow.avif", opts: ["Cow","Goat","Pig","Horse"]},
        {w: "Sheep", img: "photo/Sheep.avif", opts: ["Goat","Sheep","Horse","Cow"]}
    ]},
    { name: "Màu sắc", words: [
        {w: "Red", img: "photo/Red.avif", opts: ["Blue","Red","Green","Yellow"]},
        {w: "Blue", img: "photo/Blue.avif", opts: ["Blue","Pink","Black","White"]},
        {w: "Green", img: "photo/Green.avif", opts: ["Red","Green","Purple","Brown"]},
        {w: "Yellow", img: "photo/Yellow.avif", opts: ["Orange","Yellow","White","Blue"]},
        {w: "Orange", img: "photo/Orange.avif", opts: ["Red","Yellow","Pink","Orange"]},
        {w: "Pink", img: "photo/Pink.avif", opts: ["Purple","Red","Pink","White"]},
        {w: "Purple", img: "photo/Purple.avif", opts: ["Blue","Purple","Black","Pink"]},
        {w: "Black", img: "photo/Black.avif", opts: ["Black","White","Gray","Brown"]},
        {w: "White", img: "photo/White.avif", opts: ["White","Gray","Yellow","Blue"]},
        {w: "Brown", img: "photo/Brown.avif", opts: ["Black","Orange","Red","Brown"]}
    ]},
    { name: "Số đếm", words: [
        {w: "One", img: "photo/One.avif", opts: ["One","Two","Three","Four"]},
        {w: "Two", img: "photo/Two.avif", opts: ["Five","Two","Six","One"]},
        {w: "Three", img: "photo/Three.avif", opts: ["Three","Seven","Eight","Nine"]},
        {w: "Four", img: "photo/Four.avif", opts: ["Six","Five","Four","Three"]},
        {w: "Five", img: "photo/Five.avif", opts: ["Four","Six","Seven","Five"]},
        {w: "Six", img: "photo/Six.avif", opts: ["Seven","Six","Eight","Five"]},
        {w: "Seven", img: "photo/Seven.avif", opts: ["Nine","Eight","Seven","Six"]},
        {w: "Eight", img: "photo/Eight.avif", opts: ["Nine","Eight","Ten","Seven"]},
        {w: "Nine", img: "photo/Nine.avif", opts: ["Eight","Ten","One","Nine"]},
        {w: "Ten", img: "photo/Ten.avif", opts: ["Ten","Nine","Eight","Seven"]}
    ]},
    { name: "Gia đình", words: [
        {w: "Mother", img: "photo/Mother.avif", opts: ["Father","Mother","Baby","Sister"]},
        {w: "Father", img: "photo/Father.avif", opts: ["Brother","Father","Uncle","Grandpa"]},
        {w: "Baby", img: "photo/Baby.avif", opts: ["Baby","Mom","Dad","Teacher"]},
        {w: "Sister", img: "photo/Sister.avif", opts: ["Aunt","Brother","Sister","Mother"]},
        {w: "Brother", img: "photo/Brother.avif", opts: ["Cousin","Sister","Brother","Father"]},
        {w: "Grandmother", img: "photo/Grandmother.avif", opts: ["Grandmother","Grandfather","Aunt","Mother"]},
        {w: "Grandfather", img: "photo/Grandfather.avif", opts: ["Father","Grandmother","Uncle","Grandfather"]},
        {w: "Uncle", img: "photo/Uncle.avif", opts: ["Father","Aunt","Uncle","Grandpa"]},
        {w: "Aunt", img: "photo/Aunt.avif", opts: ["Aunt","Uncle","Mother","Grandma"]},
        {w: "Family", img: "photo/Family.avif", opts: ["Friend","Family","Teacher","Doctor"]}
    ]},
    { name: "Cơ thể", words: [
        {w: "Hand", img: "photo/Hand.avif", opts: ["Foot","Hand","Arm","Leg"]},
        {w: "Eye", img: "photo/Eye.avif", opts: ["Ear","Eye","Nose","Mouth"]},
        {w: "Nose", img: "photo/Nose.avif", opts: ["Nose","Lips","Face","Hair"]},
        {w: "Mouth", img: "photo/Mouth.avif", opts: ["Mouth","Nose","Eye","Ear"]},
        {w: "Ear", img: "photo/Ear.avif", opts: ["Nose","Eye","Ear","Mouth"]},
        {w: "Foot", img: "photo/Foot.avif", opts: ["Arm","Hand","Leg","Foot"]},
        {w: "Leg", img: "photo/Leg.avif", opts: ["Arm","Leg","Foot","Hand"]},
        {w: "Arm", img: "photo/Arm.avif", opts: ["Hand","Leg","Arm","Foot"]},
        {w: "Finger", img: "photo/Finger.avif", opts: ["Finger","Toe","Hand","Foot"]},
        {w: "Head", img: "photo/Head.avif", opts: ["Face","Head","Hair","Neck"]}
    ]},
    { name: "Quần áo", words: [
        {w: "Hat", img: "photo/Hat.avif", opts: ["Shoe","Hat","Sock","Shirt"]},
        {w: "Shirt", img: "photo/Shirt.avif", opts: ["Pants","Shirt","Skirt","Coat"]},
        {w: "Dress", img: "photo/Dress.avif", opts: ["Dress","Tie","Belt","Bag"]},
        {w: "Shoes", img: "photo/Shoes.avif", opts: ["Shoes","Socks","Boots","Sandals"]},
        {w: "Socks", img: "photo/Socks.avif", opts: ["Pants","Shoes","Socks","Hat"]},
        {w: "Pants", img: "photo/Pants.avif", opts: ["Shirt","Pants","Dress","Skirt"]},
        {w: "Skirt", img: "photo/Skirt.avif", opts: ["Skirt","Dress","Pants","Shirt"]},
        {w: "Coat", img: "photo/Coat.avif", opts: ["Gloves","Shirt","Hat","Coat"]},
        {w: "Gloves", img: "photo/Gloves.avif", opts: ["Gloves","Socks","Shoes","Hat"]},
        {w: "Scarf", img: "photo/Scarf.avif", opts: ["Coat","Scarf","Hat","Tie"]}
    ]},
    { name: "Thời tiết", words: [
        {w: "Sun", img: "photo/Sun.avif", opts: ["Moon","Sun","Cloud","Rain"]},
        {w: "Rain", img: "photo/Rain.avif", opts: ["Wind","Snow","Rain","Storm"]},
        {w: "Cloud", img: "photo/Cloud.avif", opts: ["Sky","Cloud","Star","Sun"]},
        {w: "Snow", img: "photo/Snow.avif", opts: ["Rain","Snow","Wind","Ice"]},
        {w: "Wind", img: "photo/Wind.avif", opts: ["Sun","Storm","Wind","Rain"]},
        {w: "Storm", img: "photo/Storm.avif", opts: ["Storm","Wind","Cloud","Rain"]},
        {w: "Rainbow", img: "photo/Rainbow.avif", opts: ["Sky","Rainbow","Star","Moon"]},
        {w: "Moon", img: "photo/Moon.avif", opts: ["Moon","Sun","Star","Cloud"]},
        {w: "Star", img: "photo/Star.avif", opts: ["Moon","Star","Sun","Sky"]},
        {w: "Sky", img: "photo/Sky.avif", opts: ["Sky","Cloud","Blue","Sun"]}
    ]},
    { name: "Đồ chơi", words: [
        {w: "Ball", img: "photo/Ball.avif", opts: ["Car","Ball","Doll","Lego"]},
        {w: "Car", img: "photo/Car.avif", opts: ["Plane","Car","Train","Boat"]},
        {w: "Doll", img: "photo/Doll.avif", opts: ["Doll","Bear","Robot","Bike"]},
        {w: "Bear", img: "photo/Bear.avif", opts: ["Bear","Doll","Dog","Cat"]},
        {w: "Robot", img: "photo/Robot.avif", opts: ["Train","Car","Plane","Robot"]},
        {w: "Bike", img: "photo/Bike.avif", opts: ["Car","Bike","Bus","Plane"]},
        {w: "Plane", img: "photo/Plane.avif", opts: ["Plane","Car","Boat","Train"]},
        {w: "Boat", img: "photo/Boat.avif", opts: ["Plane","Ship","Boat","Car"]},
        {w: "Train", img: "photo/Train.avif", opts: ["Train","Bus","Truck","Car"]},
        {w: "Kite", img: "photo/Kite.avif", opts: ["Cloud","Bird","Plane","Kite"]}
    ]},
    { name: "Nghề nghiệp", words: [
        {w: "Doctor", img: "photo/Doctor.avif", opts: ["Nurse","Doctor","Cook","Pilot"]},
        {w: "Teacher", img: "photo/Teacher.avif", opts: ["Singer","Farmer","Teacher","Police"]},
        {w: "Police", img: "photo/Police.avif", opts: ["Driver","Artist","Police","Dentist"]},
        {w: "Chef", img: "photo/Chef.avif", opts: ["Chef","Baker","Waiter","Worker"]},
        {w: "Farmer", img: "photo/Farmer.avif", opts: ["Gardener","Farmer","Vet","Pilot"]},
        {w: "Pilot", img: "photo/Pilot.avif", opts: ["Driver","Astronaut","Sailor","Pilot"]},
        {w: "Nurse", img: "photo/Nurse.avif", opts: ["Nurse","Doctor","Dentist","Scientist"]},
        {w: "Singer", img: "photo/Singer.avif", opts: ["Dancer","Actor","Singer","Writer"]},
        {w: "Fireman", img: "photo/Fireman.avif", opts: ["Fireman","Soldier","Police","Worker"]},
        {w: "Dentist", img: "photo/Dentist.avif", opts: ["Doctor","Nurse","Dentist","Vet"]}
    ]},
    { name: "Hình khối", words: [
        {w: "Circle", img: "photo/Circle.avif", opts: ["Square","Circle","Star","Heart"]},
        {w: "Square", img: "photo/Square.avif", opts: ["Oval","Cube","Square","Line"]},
        {w: "Triangle", img: "photo/Triangle.avif", opts: ["Box","Circle","Triangle","Star"]},
        {w: "Star", img: "photo/Star.avif", opts: ["Moon","Sun","Star","Dot"]},
        {w: "Heart", img: "photo/Heart.avif", opts: ["Heart","Star","Circle","Oval"]},
        {w: "Oval", img: "photo/Oval.avif", opts: ["Round","Oval","Square","Cube"]},
        {w: "Rectangle", img: "photo/Rectangle.avif", opts: ["Square","Box","Rectangle","Line"]},
        {w: "Diamond", img: "photo/Diamond.avif", opts: ["Star","Circle","Heart","Diamond"]},
        {w: "Cube", img: "photo/Cube.avif", opts: ["Box","Cube","Square","Sphere"]},
        {w: "Cylinder", img: "photo/Cylinder.avif", opts: ["Cylinder","Tube","Cone","Round"]}
    ]},
    { name: "Cảm xúc", words: [
        {w: "Happy", img: "photo/Happy.avif", opts: ["Sad","Happy","Angry","Sleepy"]},
        {w: "Sad", img: "photo/Sad.avif", opts: ["Funny","Brave","Scared","Sad"]},
        {w: "Angry", img: "photo/Angry.avif", opts: ["Angry","Calm","Tired","Shy"]},
        {w: "Sleepy", img: "photo/Sleepy.avif", opts: ["Bored","Sleepy","Happy","Sick"]},
        {w: "Scared", img: "photo/Scared.avif", opts: ["Brave","Scared","Angry","Funny"]},
        {w: "Surprised", img: "photo/Surprised.avif", opts: ["Surprised","Shy","Calm","Sad"]},
        {w: "Hungry", img: "photo/Hungry.avif", opts: ["Thirsty","Hungry","Full","Hot"]},
        {w: "Thirsty", img: "photo/Thirsty.avif", opts: ["Cold","Sick","Hungry","Thirsty"]},
        {w: "Sick", img: "photo/Sick.avif", opts: ["Sick","Healthy","Tired","Sad"]},
        {w: "Brave", img: "photo/Brave.avif", opts: ["Scared","Strong","Brave","Weak"]}
    ]},
    { name: "Giao thông", words: [
        {w: "Car", img: "photo/Car.avif", opts: ["Bus","Car","Bike","Boat"]},
        {w: "Bicycle", img: "photo/Bicycle.avif", opts: ["Motorbike","Bicycle","Scooter","Car"]},
        {w: "Bus", img: "photo/Bus.avif", opts: ["Train","Truck","Bus","Van"]},
        {w: "Train", img: "photo/Train.avif", opts: ["Ship","Train","Plane","Bus"]},
        {w: "Airplane", img: "photo/Airplane.avif", opts: ["Rocket","Airplane","Helicopter","Bird"]},
        {w: "Boat", img: "photo/Boat.avif", opts: ["Boat","Ship","Canoe","Submarine"]},
        {w: "Motorbike", img: "photo/Motorbike.avif", opts: ["Bike","Van","Scooter","Motorbike"]},
        {w: "Truck", img: "photo/Truck.avif", opts: ["Car","Truck","Lorry","Jeep"]},
        {w: "Helicopter", img: "photo/Helicopter.avif", opts: ["Helicopter","Plane","Drone","Rocket"]},
        {w: "Ship", img: "photo/Ship.avif", opts: ["Boat","Ship","Yacht","Submarine"]}
    ]},
    { name: "Động vật biển", words: [
        {w: "Fish", img: "photo/Fish.avif", opts: ["Crab","Fish","Shark","Whale"]},
        {w: "Shark", img: "photo/Shark.avif", opts: ["Shark","Dolphin","Whale","Seal"]},
        {w: "Dolphin", img: "photo/Dolphin.avif", opts: ["Octopus","Turtle","Fish","Dolphin"]},
        {w: "Octopus", img: "photo/Octopus.avif", opts: ["Squid","Starfish","Octopus","Jellyfish"]},
        {w: "Turtle", img: "photo/Turtle.avif", opts: ["Crab","Turtle","Frog","Snail"]},
        {w: "Whale", img: "photo/Whale.avif", opts: ["Whale","Shark","Fish","Seal"]},
        {w: "Crab", img: "photo/Crab.avif", opts: ["Lobster","Crab","Shrimp","Shell"]},
        {w: "Starfish", img: "photo/Starfish.avif", opts: ["Starfish","Shell","Coral","Fish"]},
        {w: "Seahorse", img: "photo/Seahorse.avif", opts: ["Snake","Eel","Seahorse","Fish"]},
        {w: "Jellyfish", img: "photo/Jellyfish.avif", opts: ["Octopus","Jellyfish","Coral","Water"]}
    ]},
    { name: "Phòng khách", words: [
        {w: "Sofa", img: "photo/Sofa.avif", opts: ["Chair","Bed","Sofa","Desk"]},
        {w: "Television", img: "photo/Television.avif", opts: ["Radio","Television","Phone","Computer"]},
        {w: "Clock", img: "photo/Clock.avif", opts: ["Watch","Clock","Mirror","Door"]},
        {w: "Table", img: "photo/Table.avif", opts: ["Desk","Box","Chair","Table"]},
        {w: "Chair", img: "photo/Chair.avif", opts: ["Sofa","Chair","Stool","Bed"]},
        {w: "Lamp", img: "photo/Lamp.avif", opts: ["Light","Lamp","Sun","Flashlight"]},
        {w: "Picture", img: "photo/Picture.avif", opts: ["Picture","Window","Wall","Mirror"]},
        {w: "Curtain", img: "photo/Curtain.avif", opts: ["Blinds","Curtain","Door","Sheet"]},
        {w: "Carpet", img: "photo/Carpet.avif", opts: ["Mat","Tile","Floor","Carpet"]},
        {w: "Remote", img: "photo/Remote.avif", opts: ["Phone","Keys","Remote","Game"]}
    ]},
    { name: "Hành động", words: [
        {w: "Run", img: "photo/Run.avif", opts: ["Walk","Run","Jump","Dance"]},
        {w: "Jump", img: "photo/Jump.avif", opts: ["Sit","Stand","Jump","Climb"]},
        {w: "Swim", img: "photo/Swim.avif", opts: ["Dive","Swim","Float","Bathe"]},
        {w: "Dance", img: "photo/Dance.avif", opts: ["Dance","Sing","Play","Read"]},
        {w: "Sing", img: "photo/Sing.avif", opts: ["Talk","Sing","Shout","Listen"]},
        {w: "Eat", img: "photo/Eat.avif", opts: ["Cook","Bake","Drink","Eat"]},
        {w: "Drink", img: "photo/Drink.avif", opts: ["Pour","Drink","Eat","Wash"]},
        {w: "Read", img: "photo/Read.avif", opts: ["Write","Draw","Read","Look"]},
        {w: "Write", img: "photo/Write.avif", opts: ["Paint","Type","Erase","Write"]},
        {w: "Sleep", img: "photo/Sleep.avif", opts: ["Dream","Sleep","Rest","Lie"]}
    ]},
    { name: "Động vật hoang dã", words: [
        {w: "Lion", img: "photo/Lion.avif", opts: ["Tiger","Wolf","Cat","Lion"]},
        {w: "Tiger", img: "photo/Tiger.avif", opts: ["Leopard","Lion","Tiger","Bear"]},
        {w: "Elephant", img: "photo/Elephant.avif", opts: ["Hippo","Elephant","Rhino","Giraffe"]},
        {w: "Monkey", img: "photo/Monkey.avif", opts: ["Gorilla","Monkey","Panda","Chimp"]},
        {w: "Giraffe", img: "photo/Giraffe.avif", opts: ["Deer","Horse","Giraffe","Camel"]},
        {w: "Zebra", img: "photo/Zebra.avif", opts: ["Horse","Donkey","Zebra","Pony"]},
        {w: "Bear", img: "photo/Bear.avif", opts: ["Panda","Bear","Koala","Wolf"]},
        {w: "Snake", img: "photo/Snake.avif", opts: ["Lizard","Snake","Worm","Frog"]},
        {w: "Crocodile", img: "photo/Crocodile.avif", opts: ["Crocodile","Alligator","Turtle","Fish"]},
        {w: "Hippo", img: "photo/Hippo.avif", opts: ["Elephant","Rhino","Pig","Hippo"]}
    ]},
    { name: "Thời gian", words: [
        {w: "Day", img: "photo/Day.avif", opts: ["Night","Day","Noon","Week"]},
        {w: "Night", img: "photo/Night.avif", opts: ["Morning","Evening","Night","Dark"]},
        {w: "Morning", img: "photo/Morning.avif", opts: ["Sunrise","Morning","Noon","Early"]},
        {w: "Evening", img: "photo/Evening.avif", opts: ["Evening","Afternoon","Sunset","Late"]},
        {w: "Today", img: "photo/Today.avif", opts: ["Today","Yesterday","Tomorrow","Now"]},
        {w: "Week", img: "photo/Week.avif", opts: ["Month","Year","Week","Day"]},
        {w: "Month", img: "photo/Month.avif", opts: ["Season","Month","Week","Year"]},
        {w: "Year", img: "photo/Year.avif", opts: ["Decade","Time","Century","Year"]},
        {w: "Second", img: "photo/Second.avif", opts: ["Minute","Second","Hour","Moment"]},
        {w: "Minute", img: "photo/Minute.avif", opts: ["Hour","Second","Minute","Time"]}
    ]},
    { name: "Đồ dùng học tập", words: [
        {w: "Pencil", img: "photo/Pencil.avif", opts: ["Pencil","Pen","Ruler","Crayon"]},
        {w: "Book", img: "photo/Book.avif", opts: ["Notebook","Book","Paper","Story"]},
        {w: "Bag", img: "photo/Bag.avif", opts: ["Backpack","Box","Case","Bag"]},
        {w: "Ruler", img: "photo/Ruler.avif", opts: ["Stick","Ruler","Tape","Measure"]},
        {w: "Eraser", img: "photo/Eraser.avif", opts: ["Rubber","Eraser","Sharpener","Pen"]},
        {w: "Crayon", img: "photo/Crayon.avif", opts: ["Crayon","Marker","Paint","Pencil"]},
        {w: "Glue", img: "photo/Glue.avif", opts: ["Tape","Paste","Sticky","Glue"]},
        {w: "Scissors", img: "photo/Scissors.avif", opts: ["Knife","Cut","Paper","Scissors"]},
        {w: "Desk", img: "photo/Desk.avif", opts: ["Table","Desk","Chair","Shelf"]},
        {w: "Classroom", img: "photo/Classroom.avif", opts: ["School","Library","Classroom","Gym"]}
    ]},
    { name: "Vị trí", words: [
        {w: "On", img: "photo/On.avif", opts: ["In","Under","On","Over"]},
        {w: "In", img: "photo/In.avif", opts: ["Out","In","Between","Beside"]},
        {w: "Under", img: "photo/Under.avif", opts: ["Above","Below","Under","Top"]},
        {w: "Behind", img: "photo/Behind.avif", opts: ["Behind","Front","Beside","Near"]},
        {w: "Front", img: "photo/Front.avif", opts: ["Back","Middle","Front","Side"]},
        {w: "Between", img: "photo/Between.avif", opts: ["Among","Next to","Between","Near"]},
        {w: "Next to", img: "photo/Next to.avif", opts: ["Far","Next to","Beside","Opposite"]},
        {w: "Near", img: "photo/Near.avif", opts: ["Away","Close","Near","Far"]},
        {w: "Far", img: "photo/Far.avif", opts: ["Far","Long","Near","Short"]},
        {w: "Middle", img: "photo/Middle.avif", opts: ["Center","Edge","Middle","Corner"]}
    ]},
    { name: "Thức ăn", words: [
        {w: "Bread", img: "photo/Bread.avif", opts: ["Cake","Bread","Rice","Toast"]},
        {w: "Milk", img: "photo/Milk.avif", opts: ["Water","Juice","Milk","Soda"]},
        {w: "Egg", img: "photo/Egg.avif", opts: ["Meat","Fish","Egg","Cheese"]},
        {w: "Meat", img: "photo/Meat.avif", opts: ["Steak","Meat","Chicken","Pork"]},
        {w: "Cheese", img: "photo/Cheese.avif", opts: ["Cheese","Butter","Milk","Yogurt"]},
        {w: "Rice", img: "photo/Rice.avif", opts: ["Grain","Rice","Corn","Bean"]},
        {w: "Noodles", img: "photo/Noodles.avif", opts: ["Pasta","Soup","Spaghetti","Noodles"]},
        {w: "Soup", img: "photo/Soup.avif", opts: ["Drink","Water","Soup","Broth"]},
        {w: "Pizza", img: "photo/Pizza.avif", opts: ["Burger","Pizza","Sandwich","Bread"]},
        {w: "Hamburger", img: "photo/Hamburger.avif", opts: ["Hamburger","Fries","Pizza","Hotdog"]}
    ]},
    { name: "Nhà bếp", words: [
        {w: "Spoon", img: "photo/Spoon.avif", opts: ["Spoon","Fork","Knife","Ladle"]},
        {w: "Fork", img: "photo/Fork.avif", opts: ["Spoon","Fork","Tool","Stick"]},
        {w: "Knife", img: "photo/Knife.avif", opts: ["Sharp","Sword","Blade","Knife"]},
        {w: "Bowl", img: "photo/Bowl.avif", opts: ["Plate","Bowl","Cup","Pot"]},
        {w: "Plate", img: "photo/Plate.avif", opts: ["Dish","Tray","Plate","Mat"]},
        {w: "Cup", img: "photo/Cup.avif", opts: ["Cup","Glass","Mug","Bottle"]},
        {w: "Glass", img: "photo/Glass.avif", opts: ["Plastic","Glass","Vase","Jar"]},
        {w: "Pot", img: "photo/Pot.avif", opts: ["Pan","Kettle","Pot","Stove"]},
        {w: "Pan", img: "photo/Pan.avif", opts: ["Fryer","Pan","Skillet","Pot"]},
        {w: "Fridge", img: "photo/Fridge.avif", opts: ["Box","Freezer","Fridge","Cooler"]}
    ]},
    { name: "Thể thao", words: [
        {w: "Football", img: "photo/Football.avif", opts: ["Soccer","Ball","Football","Goal"]},
        {w: "Basketball", img: "photo/Basketball.avif", opts: ["Hoop","Basketball","Net","Team"]},
        {w: "Swimming", img: "photo/Swimming.avif", opts: ["Swimming","Diving","Pool","Water"]},
        {w: "Running", img: "photo/Running.avif", opts: ["Walking","Racing","Track","Running"]},
        {w: "Tennis", img: "photo/Tennis.avif", opts: ["Badminton","Tennis","Racket","Table"]},
        {w: "Baseball", img: "photo/Baseball.avif", opts: ["Baseball","Bat","Glove","Pitch"]},
        {w: "Skating", img: "photo/Skating.avif", opts: ["Skiing","Skating","Ice","Roller"]},
        {w: "Skiing", img: "photo/Skiing.avif", opts: ["Snow","Mountain","Skiing","Cold"]},
        {w: "Cycling", img: "photo/Cycling.avif", opts: ["Driving","Biking","Cycling","Riding"]},
        {w: "Yoga", img: "photo/Yoga.avif", opts: ["Yoga","Stretch","Exercise","Quiet"]}
    ]},
    { name: "Thời tiết nâng cao", words: [
        {w: "Snowman", img: "photo/Snowman.avif", opts: ["Ice","Winter","Snowman","Cold"]},
        {w: "Thunder", img: "photo/Thunder.avif", opts: ["Lightning","Thunder","Noise","Sky"]},
        {w: "Lightning", img: "photo/Lightning.avif", opts: ["Flash","Lightning","Electric","Rain"]},
        {w: "Windy", img: "photo/Windy.avif", opts: ["Windy","Breezy","Airy","Stormy"]},
        {w: "Foggy", img: "photo/Foggy.avif", opts: ["Foggy","Misty","Grey","Cloudy"]},
        {w: "Sunny", img: "photo/Sunny.avif", opts: ["Hot","Sunny","Bright","Clear"]},
        {w: "Cloudy", img: "photo/Cloudy.avif", opts: ["Grey","Dark","Cloudy","Sky"]},
        {w: "Freezing", img: "photo/Freezing.avif", opts: ["Icy","Cold","Freezing","Chill"]},
        {w: "Stormy", img: "photo/Stormy.avif", opts: ["Rough","Heavy","Dark","Stormy"]},
        {w: "Hurricane", img: "photo/Hurricane.avif", opts: ["Tornado","Cyclone","Wind","Hurricane"]}
    ]},
    { name: "Nơi chốn", words: [
        {w: "Park", img: "photo/Park.avif", opts: ["Park","Garden","Playground","Field"]},
        {w: "Beach", img: "photo/Beach.avif", opts: ["Ocean","Beach","Sand","Island"]},
        {w: "Farm", img: "photo/Farm.avif", opts: ["Farm","Barn","Country","Field"]},
        {w: "Market", img: "photo/Market.avif", opts: ["Market","Shop","Grocery","Store"]},
        {w: "Supermarket", img: "photo/Supermarket.avif", opts: ["Mall","Building","Supermarket","Hall"]},
        {w: "Library", img: "photo/Library.avif", opts: ["Bookshelf","Library","School","Quiet"]},
        {w: "Hospital", img: "photo/Hospital.avif", opts: ["Clinic","Health","Hospital","Bed"]},
        {w: "Zoo", img: "photo/Zoo.avif", opts: ["Cage","Park","Animals","Zoo"]},
        {w: "Museum", img: "photo/Museum.avif", opts: ["Art","History","Gallery","Museum"]},
        {w: "Bakery", img: "photo/Bakery.avif", opts: ["Bakery","Bread","Cake","Cafe"]}
    ]},
    { name: "Giao thông nâng cao", words: [
        {w: "Rocket", img: "photo/Rocket.avif", opts: ["Rocket","Space","Shuttle","Star"]},
        {w: "Ambulance", img: "photo/Ambulance.avif", opts: ["Van","Ambulance","Doctor","Hospital"]},
        {w: "Fire truck", img: "photo/Fire_truck.avif", opts: ["Fire truck","Lorry","Red","Water"]},
        {w: "Submarine", img: "photo/Submarine.avif", opts: ["Submarine","Ship","Underwater","Deep"]},
        {w: "Tractor", img: "photo/Tractor.avif", opts: ["Truck","Tractor","Farm","Field"]},
        {w: "Balloon", img: "photo/Balloon.avif", opts: ["Air","Balloon","Basket","Sky"]},
        {w: "Van", img: "photo/Van.avif", opts: ["Mini","Car","Van","Truck"]},
        {w: "Scooter", img: "photo/Scooter.avif", opts: ["Vespa","Bike","Wheel","Scooter"]},
        {w: "Police car", img: "photo/Police_car.avif", opts: ["Taxi","Officer","Blue","Police car"]},
        {w: "Taxi", img: "photo/Taxi.avif", opts: ["Uber","Yellow","Taxi","Driver"]}
    ]},
    { name: "Gia đình nâng cao", words: [
        {w: "Grandpa", img: "photo/Grandpa.avif", opts: ["Old","Grandpa","Man","Father"]},
        {w: "Grandma", img: "photo/Grandma.avif", opts: ["Woman","Grandma","Old","Mother"]},
        {w: "Son", img: "photo/Son.avif", opts: ["Son","Boy","Child","Baby"]},
        {w: "Daughter", img: "photo/Daughter.avif", opts: ["Daughter","Girl","Child","Kid"]},
        {w: "Parents", img: "photo/Parents.avif", opts: ["Couple","Parents","Home","Grown-ups"]},
        {w: "Children", img: "photo/Children.avif", opts: ["Kids","Class","Children","Play"]},
        {w: "Grandchildren", img: "photo/Grandchildren.avif", opts: ["Small","Young","Family","Grandchildren"]},
        {w: "Cousin", img: "photo/Cousin.avif", opts: ["Friend","Cousin","Relative","Twin"]},
        {w: "Auntie", img: "photo/Auntie.avif", opts: ["Lady","Mother","Woman","Auntie"]},
        {w: "Neighbor", img: "photo/Neighbor.avif", opts: ["House","Street","Neighbor","Friend"]}
    ]},
    { name: "Thiên nhiên nâng cao", words: [
        {w: "Stone", img: "photo/Stone.avif", opts: ["Stone","Rock","Pebble","Hard"]},
        {w: "Sand", img: "photo/Sand.avif", opts: ["Dust","Sand","Beach","Desert"]},
        {w: "Shell", img: "photo/Shell.avif", opts: ["Spiral","Sea","Shell","Shore"]},
        {w: "Wave", img: "photo/Wave.avif", opts: ["Water","Surf","Wave","Tide"]},
        {w: "Mountain", img: "photo/Mountain.avif", opts: ["Hill","Peak","Climb","Mountain"]},
        {w: "Volcano", img: "photo/Volcano.avif", opts: ["Lava","Volcano","Fire","Ash"]},
        {w: "Waterfall", img: "photo/Waterfall.avif", opts: ["Lake","Stream","River","Waterfall"]},
        {w: "Island", img: "photo/Island.avif", opts: ["Island","Earth","Map","Palms"]},
        {w: "Cave", img: "photo/Cave.avif", opts: ["Hole","Cave","Dark","Stone"]},
        {w: "Desert", img: "photo/Desert.avif", opts: ["Desert","Dry","Hot","Sand"]}
    ]},
    { name: "Vũ trụ nâng cao", words: [
        {w: "Earth", img: "photo/Earth.avif", opts: ["World","Planet","Earth","Globe"]},
        {w: "Moon", img: "photo/Moon.avif", opts: ["Silver","Moon","Night","Space"]},
        {w: "Sun", img: "photo/Sun.avif", opts: ["Sun","Fire","Star","Bright"]},
        {w: "Astronaut", img: "photo/Astronaut.avif", opts: ["Hero","Astronaut","Suit","Pilot"]},
        {w: "Alien", img: "photo/Alien.avif", opts: ["Green","Monster","UFO","Alien"]},
        {w: "Planet", img: "photo/Planet.avif", opts: ["Sphere","Space","Star","Planet"]},
        {w: "Galaxy", img: "photo/Galaxy.avif", opts: ["Spiral","Galaxy","Stars","Light"]},
        {w: "Comet", img: "photo/Comet.avif", opts: ["Tail","Fire","Comet","Falling"]},
        {w: "Telescope", img: "photo/Telescope.avif", opts: ["Telescope","Glass","Stars","Look"]},
        {w: "Spaceship", img: "photo/Spaceship.avif", opts: ["Jet","Vehicle","Fly","Spaceship"]}
    ]}
];